
# 默认窗口无标题栏，16:9的窗口比例启动
window:
    decorations: "none"
    dimensions:
      columns: 84
      lines: 24

# 背景半透明，方便抄代码
background_opacity: 0.8

# 实时重载配置文件，不用重启测试配置选项
live_config_reload: true

# Colors (Ayu Mirage)
colors:
  # Default colors
  primary:
    background: '#202734'
    foreground: '#CBCCC6'

  # Normal colors
  normal:
    black: '#191E2A'
    red: '#FF3333'
    green: '#BAE67E'
    yellow: '#FFA759'
    blue: '#73D0FF'
    magenta: '#FFD580'
    cyan: '#95E6CB'
    white: '#C7C7C7'

  # Bright colors
  bright:
    black: '#686868'
    red: '#F27983'
    green: '#A6CC70'
    yellow: '#FFCC66'
    blue: '#5CCFE6'
    magenta: '#FFEE99'
    cyan: '#95E6CB'
    white: '#FFFFFF'
# 字体设置为等宽字体，可以用命令 fc-list 查看你系统的字体
font:
  size: 10

  normal:
    family: Monospace
    style: Regular

  bold:
    family: Monospace

  italic:
    family: Monospace
