#### python packages
[yutto]
fetch.github = "yutto-dev/yutto"
src.github_tag = "yutto-dev/yutto"

# https://discourse.nixos.org/t/installing-a-python-package-from-pypi/24553/2
# 不使用 fetchPypi，原因见上面链接
[musicdl]
fetch.github = "CharlesPikachu/musicdl"
src.git = "https://github.com/CharlesPikachu/musicdl"

[about-time]
src.pypi = "about-time"
fetch.pypi = "about-time"

[alive-progress]
fetch.pypi = "alive-progress"
src.pypi = "alive-progress"

[websocket-bridge-python]
fetch.pypi = "websocket_bridge_python"
src.pypi = "websocket_bridge_python"

[httpx]
src.github = "encode/httpx"
fetch.github = "encode/httpx"

### common
[maple-sc-nf]
src.github = "subframe7536/Maple-font"
src.from_pattern = "v(.*)"
src.to_pattern = "\\1"
fetch.url = "https://github.com/subframe7536/Maple-font/releases/download/v$ver/MapleMono-SC-NF.zip"

[maple-mono]
src.github = "subframe7536/Maple-font"
src.from_pattern = "v(.*)"
src.to_pattern = "\\1"
fetch.url = "https://github.com/subframe7536/maple-font/releases/download/v$ver/MapleMono-ttf.zip"

[lazyvim-star]
src.git = "https://github.com/LazyVim/starter"
fetch.github = "LazyVim/starter"

[go-musicfox]
src.github = "go-musicfox/go-musicfox"
fetch.github = "go-musicfox/go-musicfox"
git.fetchSubmodules = false
# passthru = { vendorHash = null }

[deeplx]
src.github = "OwO-Network/DeepLX"
fetch.github = "OwO-Network/DeepLX"
passthru = { vendorHash = "sha256-x4Z8fTrgXOH+9Ixj9NKr2G3BuQPm7/CqNGoIVbXmMOE=" }

[codicons]
src.git = "https://github.com/microsoft/vscode-codicons"
fetch.url = "https://github.com/microsoft/vscode-codicons/raw/$ver/dist/codicon.ttf"

[clash2singbox]
src.github = "xmdhs/clash2singbox"
fetch.github = "xmdhs/clash2singbox"
passthru = { vendorHash = "sha256-0HpjgvxhhZ7pb5Z+K78hxdaddb/H7Sc3l1xEz4FDKaA=" }


[mihomo]
src.github = "MetaCubeX/mihomo"
fetch.github = "MetaCubeX/mihomo"
passthru = { vendorHash = "sha256-b7q0e3HHolVhwNJF0kwvwuVy8ndJLc0ITMl+0/YtSjA=" }

[musicn]
src.github = "zonemeen/musicn"
fetch.github = "zonemeen/musicn"
passthru = { npmDepsHash = "sha256-Yr0zgQBP/ocJ/ThbFhidPnkP4C8/lWufxkd3sJnqErA=" }

[firefox-utils]
src.git = "https://github.com/xiaoxiaoflood/firefox-scripts"
fetch.url = "https://github.com/xiaoxiaoflood/firefox-scripts/raw/$ver/utils.zip"

[seam]
src.github = "Borber/seam"
fetch.github = "Borber/seam"
# passthru = { cargoHash = "sha256-SFwNYyZ/qzWlIwV2c8Tot+RyQtTNb559jK4GCGtWjNk=" }
cargo_locks = ["Cargo.lock"]

[bbdown]
src.git = "https://github.com/nilaoda/BBDown"
fetch.github = "nilaoda/BBDown"

[alist]
src.github = "alist-org/alist"
fetch.github = "alist-org/alist"
passthru = { vendorHash = "sha256-5APKL65KKvpOJ6KE5ccA4S/AAy1fhdovc1d+L0rq0Ks=" }

[alist-web]
src.github = "alist-org/alist-web"
fetch.url = "https://github.com/alist-org/alist-web/releases/download/$ver/dist.tar.gz"

### darwin
[yabai-zsh-completions]
src.git = "https://github.com/Amar1729/yabai-zsh-completions"
fetch.github = "Amar1729/yabai-zsh-completions"

[pngpaste]
src.github_tag = "jcsalterego/pngpaste"
fetch.github = "jcsalterego/pngpaste"

[dutis]
src.git = "https://github.com/tsonglew/dutis"
fetch.github = "tsonglew/dutis"
passthru = { vendorHash = "sha256-lUBSQq4ac/Vc76gmSaKFkfCrO/BmhQU+3UyA+URb8l8=" }
git.fetchSubmodules = false

[emacsclient]
src.git = "https://github.com/nashamri/spacemacs-logo"
fetch.url = "https://github.com/nashamri/spacemacs-logo/raw/$ver/spacemacs.icns"

[lporg]
src.github = "blacktop/lporg"
fetch.github = "blacktop/lporg"
passthru = { vendorHash = "sha256-GQaIfUtM3iDQ9jmrSMqYvcPysigdu7w10xGDIYv4OY8=" }

### DarwinAPP

[chatgpt]
src.github="lencx/ChatGPT"
src.from_pattern = "v(.*)"
src.to_pattern = "\\1"
fetch.url = "https://github.com/lencx/ChatGPT/releases/download/v$ver/ChatGPT_$ver_macos_aarch64.dmg"

[next-chat]
src.github="ChatGPTNextWeb/ChatGPT-Next-Web"
src.from_pattern = "v(.*)"
src.to_pattern = "\\1"
fetch.url = "https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/releases/download/v$ver/NextChat_$ver_x64.dmg"

[clash-nyanpasu]
src.github="keiko233/clash-nyanpasu"
src.from_pattern = "v(.*)"
src.to_pattern = "\\1"
fetch.url = "https://github.com/keiko233/clash-nyanpasu/releases/download/v$ver/Clash.Nyanpasu_$ver_aarch64.dmg"

[clash-verge]
src.github="zzzgydi/clash-verge"
src.from_pattern = "v(.*)"
src.to_pattern = "\\1"
fetch.url = "https://github.com/zzzgydi/clash-verge/releases/download/v$ver/Clash.Verge_$ver_aarch64.dmg"

[iina]
src.github="iina/iina"
src.from_pattern = "v(.*)"
src.to_pattern = "\\1"
fetch.url = "https://github.com/iina/iina/releases/download/v$ver/IINA.v$ver.dmg"

[iinaplus]
src.github="xjbeta/iina-plus"
src.from_pattern = "v(.*)"
src.to_pattern = "\\1"
fetch.url = "https://github.com/xjbeta/iina-plus/releases/download/$ver/IINA+.$ver.dmg"

[localsend]
src.github="localsend/localsend"
src.from_pattern = "v(.*)"
src.to_pattern = "\\1"
fetch.url = "https://github.com/localsend/localsend/releases/download/v$ver/LocalSend-$ver.dmg"

[lyricx]
src.github="go-musicfox/LyricsX"
src.from_pattern = "v(.*)"
src.to_pattern = "\\1"
fetch.url = "https://github.com/go-musicfox/LyricsX/releases/download/v$ver/LyricsX_$ver.zip"

[neovide]
src.github="neovide/neovide"
src.from_pattern = "v(.*)"
src.to_pattern = "\\1"
fetch.url = "https://github.com/neovide/neovide/releases/download/$ver/neovide.dmg.zip"

[qutebrowser]
src.github="qutebrowser/qutebrowser"
src.from_pattern = "v(.*)"
src.to_pattern = "\\1"
fetch.url = "https://github.com/qutebrowser/qutebrowser/releases/download/v$ver/qutebrowser-$ver.dmg"

[upic]
src.github="gee1k/uPic"
src.from_pattern = "v(.*)"
src.to_pattern = "\\1"
fetch.url = "https://github.com/gee1k/uPic/releases/download/v$ver/uPic.zip"

[xbydriver]
src.github ="odomu/aliyunpan"
src.from_pattern = "v(.*)"
src.to_pattern = "\\1"
fetch.url = "https://github.com/odomu/aliyunpan/releases/download/v$ver/alixby-$ver-mac-arm64.dmg"

[zy-player]
src.github="Hiram-Wong/ZyPlayer"
src.from_pattern = "v(.*)"
src.to_pattern = "\\1"
fetch.url = "https://github.com/Hiram-Wong/ZyPlayer/releases/download/v$ver/zyplayer-mac-$ver-arm64.dmg"

[calibrepath]
src.github = "Cirn09/calibre-do-not-translate-my-path"
src.from_pattern = "v(.*)"
src.to_pattern = "\\1"
fetch.url = "https://github.com/Cirn09/calibre-do-not-translate-my-path/releases/download/v$ver/mac-patch-backend+update-v$ver.zip"

[calibre]
src.github = "Cirn09/calibre-do-not-translate-my-path"
src.from_pattern = "v(.*)"
src.to_pattern = "\\1"
fetch.url = "https://download.calibre-ebook.com/$ver/calibre-$ver.dmg"

[fx-folder]
src.git = "https://github.com/xiaoxiaoflood/firefox-scripts"
fetch.url = "https://github.com/xiaoxiaoflood/firefox-scripts/raw/$ver/fx-folder.zip"

[vivaldi]
src.webpage = "https://vivaldi.com/download"
src.regex = "\"https://downloads.vivaldi.com/stable/Vivaldi.([0-9.]+).universal.dmg\""
fetch.url = "https://downloads.vivaldi.com/stable/Vivaldi.$ver.universal.dmg"

["chrome.arm64"]
src.webpage = "https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions.json"
src.regex = "\"channel\":\"Stable\",\"version\":\"([0-9.]+)\""
fetch.url = "https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/$ver/mac-arm64/chrome-mac-arm64.zip"
# "https://registry.npmmirror.com/-/binary/chrome-for-testing/121.0.6167.85/mac-x64/chrome-mac-x64.zip"

["chrome.x64"]
src.webpage = "https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions.json"
src.regex = "\"channel\":\"Stable\",\"version\":\"([0-9.]+)\""
fetch.url = "https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/$ver/mac-x64/chrome-mac-x64.zip"

[ryujinx]
src.github = "Ryujinx/release-channel-master"
fetch.url = "https://github.com/Ryujinx/release-channel-master/releases/download/$ver/test-ava-ryujinx-$ver-macos_universal.app.tar.gz"

[ryusak]
src.github = "FennyFatal/RyuSAK"
src.from_pattern = "v(.*)-experimental"
src.to_pattern = "\\1"
fetch.url = "https://github.com/FennyFatal/RyuSAK/releases/download/v$ver-experimental/RyuSAK-darwin-arm64-$ver.zip"

[spotube]
src.github = "KRTirtho/spotube"
src.from_pattern = "v(.*)"
src.to_pattern = "\\1"
fetch.url = "https://github.com/KRTirtho/spotube/releases/download/v$ver/Spotube-macos-universal.dmg"

### firefox-addons
[ublock-origin]
src.github_tag = "gorhill/uBlock"
fetch.url = "https://github.com/gorhill/uBlock/releases/download/$ver/uBlock0_$ver.firefox.signed.xpi"

[sidebery]
src.github = "mbnuqw/sidebery"
fetch.github = "mbnuqw/sidebery"

[darkreader]
src.github = "darkreader/darkreader"
src.from_pattern = "v(.*)"
src.to_pattern = "\\1"
fetch.url = "https://github.com/darkreader/darkreader/releases/download/v$ver/darkreader-firefox.xpi"
