{
  pkgs,
  lib,
  config,
  options,
  my,
  ...
}:
with lib;
with my; let
  cfp = config.modules.shell;
  cfg = cfp.fish;
  fishIndent = name: text:
    pkgs.runCommand name {
      nativeBuildInputs = [cfg.package];
      inherit text;
      passAsFile = ["text"];
    } "env HOME=$(mktemp -d) fish_indent < $textPath > $out";
in {
  options.modules.shell.fish = {
    enable = mkEnableOption "Whether to use fish";

    rcInit = mkOpt' types.lines "" "Init fish shell";
    prevInit = mkOpt' types.lines "" "Init fish prevInit";
    loginInit = mkOpt' types.lines "" "Init fish login";
    extraRc = mkOpt' types.lines "" "extra fish";

    package = mkPackageOption pkgs "fish" {};
  };
  config = mkIf cfg.enable {
    home = {
      packages = [cfg.package];
      file = mkMerge [
        (mkIf (! config.home.useos) {
          ".cache/fish/preEnv.fish".source = fishIndent "preEnv.fish" ''
            source ${escapeShellArg "${config.home.profileDirectory}/etc/profile.d/hm-session-vars.sh"}
          '';
        })
        {
          ".cache/fish/env.fish".source = fishIndent "env.fish" ''
            # -*- mode: fish; -*-
            # This file is autogenerated, do not edit it!
            ${concatStringsSep "\n" (mapAttrsToList (k: v: (
                if k == "PATH"
                then concatMapStringsSep "\n" (x: "fish_add_path -g -P -p ${x} || true") v
                else
                  (
                    if builtins.isList v
                    then ''
                      if set -q ${k}
                          set -gx ${k} ${concatMapStringsSep " " builtins.toString v} ${builtins.toString "\$${k}"}
                      else
                          set -gx ${k} ${concatMapStringsSep " " builtins.toString v}
                      end
                    ''
                    else "set -gx ${k} ${v}"
                  )
              ))
              cfp.env)}
            ${cfg.prevInit}
          '';
          ".cache/fish/login.fish".source = fishIndent "login.fish" cfg.loginInit;
          ".cache/fish/interactive.fish".source = fishIndent "interactive.fish" ''
            ${concatStringsSep "\n"
              (mapAttrsToList (k: v: "alias ${k} ${escapeShellArg v}") cfp.aliases)}
            ${cfg.rcInit}
          '';
          ".cache/fish/extra.fish".source = fishIndent "extra.fish" cfg.extraRc;
        }
      ];
    };
  };
}
