# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      # <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
      "${modulesPath}/installer/scan/not-detected.nix"
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" "i915" ];
  boot.extraModulePackages = [ ];
  # My Notebook 000: 00: 16.0 hardware problem, so disable it.
  boot.blacklistedKernelModules = [ "mei" "mei_me" ];

  ## CPU
  nix.maxJobs = lib.mkDefault 3;
  nix.buildCores = lib.mkDefault 1;
  powerManagement.cpuFreqGovernor = "performance";
  hardware.cpu.intel.updateMicrocode = true;

  ## SSDs
  services.fstrim.enable = true;

  # Make ralt the compose key, so ralt+a+a =a ralt+o+/ = o
  #services.xserver.xkbOptions = "compose:ralt";

  ## GPU
  ## This laptop is n card problem, can not be used to switch the set was.
  services.xserver.videoDrivers = [ "intel" ];
  hardware.opengl.enable = true;

  # The touchpad fix errors
  services.xserver.synaptics.enable = false;
  services.xserver.libinput.naturalScrolling = false;
  services.xserver.libinput.accelProfile = "flat";
  services.xserver.libinput.enable = true;
  services.xserver.inputClassSections = [
    ''
      Identifier "Enable libinput for TrackPoint"
      MatchIsPointer "on"
      Driver "libinput"
      Option "Accel Speed" "0.1"
    ''
  ];

  # Set DPI
  services.xserver.dpi = 96;

  # Power management
  environment.systemPackages = [ pkgs.acpi ];
  powerManagement.powertop.enable = true;
  # environment.systemPackages = with pkgs; [ #
  #   (writeScriptBin "nvidia-settings" ''
  #     #!${stdenv.shell}
  #     mkdir -p "$XDG_CONFIG_HOME/nvidia"
  #     exec ${config.boot.kernelPackages.nvidia_x11.settings}/bin/nvidia-settings --config="$XDG_CONFIG_HOME/nvidia/settings"
  #   '')
  #];
  ### Harddrives
  fileSystems = {
    "/" = {
      device = "/dev/disk/by-label/nixos";
      fsType = "ext4";
      options = [ "noatime" ];
    };
    "/boot" = {
      device = "/dev/disk/by-label/BOOT";
      fsType = "vfat";
    };
    "/mnt/archive" = {
      device = "/dev/disk/by-label/archive";
      fsType = "xfs";
      options = [ "noatime" ];
    };
  };
  swapDevices = [ { device = "/var/swapfile"; size = 4096 ; priority = 30; } ];

  # zram startup
  zramSwap = { enable = true; priority = 50 ; };
}
