# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  about-time = {
    pname = "about-time";
    version = "4.2.1";
    src = fetchurl {
      url = "https://pypi.org/packages/source/a/about-time/about-time-4.2.1.tar.gz";
      sha256 = "sha256-alOIYtM85n2ZdCnRSZgxDh2/2my32bv795nEcJhH/s4=";
    };
  };
  alist = {
    pname = "alist";
    version = "v3.30.0";
    src = fetchFromGitHub {
      owner = "alist-org";
      repo = "alist";
      rev = "v3.30.0";
      fetchSubmodules = false;
      sha256 = "sha256-MW9QtH7nR1Zaepi1snwgbzPK7XjFDKlFoKG/KYjH9dM=";
    };
    vendorHash = "sha256-5APKL65KKvpOJ6KE5ccA4S/AAy1fhdovc1d+L0rq0Ks=";
  };
  alist-web = {
    pname = "alist-web";
    version = "3.30.0";
    src = fetchurl {
      url = "https://github.com/alist-org/alist-web/releases/download/3.30.0/dist.tar.gz";
      sha256 = "sha256-BOFg78bnFpEDzUJKOd4PFyDnaarMSdwKL8w/H8xtD+4=";
    };
  };
  alive-progress = {
    pname = "alive-progress";
    version = "3.1.5";
    src = fetchurl {
      url = "https://pypi.org/packages/source/a/alive-progress/alive-progress-3.1.5.tar.gz";
      sha256 = "sha256-QuOZpmyBUNxQdgLf97eVPxBe8R+vl92qbSexy/RcTJg=";
    };
  };
  bbdown = {
    pname = "bbdown";
    version = "1196918e709f883eabfe3122ccad824b8f551381";
    src = fetchFromGitHub {
      owner = "nilaoda";
      repo = "BBDown";
      rev = "1196918e709f883eabfe3122ccad824b8f551381";
      fetchSubmodules = false;
      sha256 = "sha256-foTgCQKzYZc4aDxiAeoXR4jdEytqnkCt1Rwr2ztostM=";
    };
    date = "2023-11-13";
  };
  calibre = {
    pname = "calibre";
    version = "7.4.0";
    src = fetchurl {
      url = "https://download.calibre-ebook.com/7.4.0/calibre-7.4.0.dmg";
      sha256 = "sha256-ON3NG6F7dSaie4t31ALd2V2DX34TZu6VqMMXJi4cwic=";
    };
  };
  calibrepath = {
    pname = "calibrepath";
    version = "7.4.0";
    src = fetchurl {
      url = "https://github.com/Cirn09/calibre-do-not-translate-my-path/releases/download/v7.4.0/mac-patch-backend+update-v7.4.0.zip";
      sha256 = "sha256-VkOHhDtiA2jANSSDV5nROdIIet56oz0gqgnpy87g+5k=";
    };
  };
  chatgpt = {
    pname = "chatgpt";
    version = "1.1.0";
    src = fetchurl {
      url = "https://github.com/lencx/ChatGPT/releases/download/v1.1.0/ChatGPT_1.1.0_macos_aarch64.dmg";
      sha256 = "sha256-+HC6E1rZkHFUdMuwOLWzisuNCGQIA+LHnIeOIQ9IAPY=";
    };
  };
  "chrome.arm64" = {
    pname = "chrome.arm64";
    version = "121.0.6167.85";
    src = fetchurl {
      url = "https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/121.0.6167.85/mac-arm64/chrome-mac-arm64.zip";
      sha256 = "sha256-ZtkZoJxLVBf3Mu1XQtNAHNM9LgYAs2INKOZIZ1/t1Wc=";
    };
  };
  "chrome.x64" = {
    pname = "chrome.x64";
    version = "121.0.6167.85";
    src = fetchurl {
      url = "https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/121.0.6167.85/mac-x64/chrome-mac-x64.zip";
      sha256 = "sha256-4VAxmg+14TrbxwN3JUXHyfogsEdLVmZ/mfeWf17v4Lg=";
    };
  };
  clash-nyanpasu = {
    pname = "clash-nyanpasu";
    version = "1.4.4";
    src = fetchurl {
      url = "https://github.com/keiko233/clash-nyanpasu/releases/download/v1.4.4/Clash.Nyanpasu_1.4.4_aarch64.dmg";
      sha256 = "sha256-hE9DKwv7dVK4zYpRvI5i5pTLWIET/bQ5FKq12uce/00=";
    };
  };
  clash-verge = {
    pname = "clash-verge";
    version = "1.3.8";
    src = fetchurl {
      url = "https://github.com/zzzgydi/clash-verge/releases/download/v1.3.8/Clash.Verge_1.3.8_aarch64.dmg";
      sha256 = "sha256-/YNwMjppWogo0adIfJ50IAzja1GzJElb+6IUmMb8jEg=";
    };
  };
  clash2singbox = {
    pname = "clash2singbox";
    version = "v0.0.2";
    src = fetchFromGitHub {
      owner = "xmdhs";
      repo = "clash2singbox";
      rev = "v0.0.2";
      fetchSubmodules = false;
      sha256 = "sha256-XnjsRi5G+i6Bfh3Pq7uQYZmN2IOIrVjz74D4mmXq6zY=";
    };
    vendorHash = "sha256-0HpjgvxhhZ7pb5Z+K78hxdaddb/H7Sc3l1xEz4FDKaA=";
  };
  codicons = {
    pname = "codicons";
    version = "6ceb091d5c40da3e5836e3d80b08d3f74efc4cbf";
    src = fetchurl {
      url = "https://github.com/microsoft/vscode-codicons/raw/6ceb091d5c40da3e5836e3d80b08d3f74efc4cbf/dist/codicon.ttf";
      sha256 = "sha256-YAjrSd1ospTk4UtrKS2rkYDcBjzXk0/mlpIaCVjilXs=";
    };
    date = "2024-01-18";
  };
  darkreader = {
    pname = "darkreader";
    version = "4.9.76";
    src = fetchurl {
      url = "https://github.com/darkreader/darkreader/releases/download/v4.9.76/darkreader-firefox.xpi";
      sha256 = "sha256-lz9mQmPcxyHRDmK12bKmHIyW/iHtPI4WDC769XTrSC0=";
    };
  };
  deeplx = {
    pname = "deeplx";
    version = "v0.8.8";
    src = fetchFromGitHub {
      owner = "OwO-Network";
      repo = "DeepLX";
      rev = "v0.8.8";
      fetchSubmodules = false;
      sha256 = "sha256-4/sfePuNS67tlyt0KGqLiYXfTu5uvHS2+XD8X5IrROo=";
    };
    vendorHash = "sha256-x4Z8fTrgXOH+9Ixj9NKr2G3BuQPm7/CqNGoIVbXmMOE=";
  };
  dutis = {
    pname = "dutis";
    version = "e8f8d6176fff1b42e7e68a552fcfd2923f9c27a2";
    src = fetchFromGitHub {
      owner = "tsonglew";
      repo = "dutis";
      rev = "e8f8d6176fff1b42e7e68a552fcfd2923f9c27a2";
      fetchSubmodules = false;
      sha256 = "sha256-mwIBWLKUbqINPc1SnsMHVaN+5sXlRvC20M6kv9DAa5I=";
    };
    vendorHash = "sha256-lUBSQq4ac/Vc76gmSaKFkfCrO/BmhQU+3UyA+URb8l8=";
    date = "2023-09-27";
  };
  emacsclient = {
    pname = "emacsclient";
    version = "917f2f2694019d534098f5e2e365b5f6e5ddbd37";
    src = fetchurl {
      url = "https://github.com/nashamri/spacemacs-logo/raw/917f2f2694019d534098f5e2e365b5f6e5ddbd37/spacemacs.icns";
      sha256 = "sha256-s9uLfPpLxbziS8TcHt47dSxxhse1TAmZTqtexOqkiQA=";
    };
    date = "2018-08-26";
  };
  fav = {
    pname = "fav";
    version = "v0.2.1";
    src = fetchFromGitHub {
      owner = "kingwingfly";
      repo = "fav";
      rev = "v0.2.1";
      fetchSubmodules = false;
      sha256 = "sha256-R6vJa9dCRz9KqMNbW/DoJGVTUlqpE6PaCROQQw8vK9I=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./fav-v0.2.1/Cargo.lock;
      outputHashes = {
        
      };
    };
  };
  firefox-utils = {
    pname = "firefox-utils";
    version = "b013243f1916576166a02d816651c2cc6416f63e";
    src = fetchurl {
      url = "https://github.com/xiaoxiaoflood/firefox-scripts/raw/b013243f1916576166a02d816651c2cc6416f63e/utils.zip";
      sha256 = "sha256-2LK3BGKSsFeMKLsXnMNz2ONJ/Wb07VTLSu4TwemYNOQ=";
    };
    date = "2023-02-24";
  };
  fx-folder = {
    pname = "fx-folder";
    version = "b013243f1916576166a02d816651c2cc6416f63e";
    src = fetchurl {
      url = "https://github.com/xiaoxiaoflood/firefox-scripts/raw/b013243f1916576166a02d816651c2cc6416f63e/fx-folder.zip";
      sha256 = "sha256-IAiHzJ/9YBuChVTePMmXFYtx69jX+crDe1GcAcfZ+OI=";
    };
    date = "2023-02-24";
  };
  go-musicfox = {
    pname = "go-musicfox";
    version = "v4.3.0";
    src = fetchFromGitHub {
      owner = "go-musicfox";
      repo = "go-musicfox";
      rev = "v4.3.0";
      fetchSubmodules = false;
      sha256 = "sha256-JDR3D3tILT0q9jqcZmbfQC3yn7cmaSL/GEpCguqCFXI=";
    };
  };
  httpx = {
    pname = "httpx";
    version = "0.26.0";
    src = fetchFromGitHub {
      owner = "encode";
      repo = "httpx";
      rev = "0.26.0";
      fetchSubmodules = false;
      sha256 = "sha256-qMMx1CYu2/yH4NRvZFzJOflAPIbcvMYJqU4r+chuzl0=";
    };
  };
  iina = {
    pname = "iina";
    version = "1.3.4";
    src = fetchurl {
      url = "https://github.com/iina/iina/releases/download/v1.3.4/IINA.v1.3.4.dmg";
      sha256 = "sha256-feUPWtSi/Vsnv1mjGyBgB0wFMxx6r6UzrUratlAo14w=";
    };
  };
  iinaplus = {
    pname = "iinaplus";
    version = "0.7.18";
    src = fetchurl {
      url = "https://github.com/xjbeta/iina-plus/releases/download/0.7.18/IINA+.0.7.18.dmg";
      sha256 = "sha256-LFIQh4BOWOJqaO3m8IvDQ4yBhCATseFHKDeP3nKlUlc=";
    };
  };
  lazyvim-star = {
    pname = "lazyvim-star";
    version = "741ff3aa70336abb6c76ee4c49815ae589a1b852";
    src = fetchFromGitHub {
      owner = "LazyVim";
      repo = "starter";
      rev = "741ff3aa70336abb6c76ee4c49815ae589a1b852";
      fetchSubmodules = false;
      sha256 = "sha256-EkDWEwXTqQIIRWmnqBMVBZ970QBbPmBW6X7n7xzYmzc=";
    };
    date = "2024-01-19";
  };
  localsend = {
    pname = "localsend";
    version = "1.13.1";
    src = fetchurl {
      url = "https://github.com/localsend/localsend/releases/download/v1.13.1/LocalSend-1.13.1.dmg";
      sha256 = "sha256-YCy6NlmEPsOFtIZ27mOYDnMPd1tj3YO2bwNDdM3K/uY=";
    };
  };
  lporg = {
    pname = "lporg";
    version = "v20.4.31";
    src = fetchFromGitHub {
      owner = "blacktop";
      repo = "lporg";
      rev = "v20.4.31";
      fetchSubmodules = false;
      sha256 = "sha256-A/OE67qAn9RHSCveiRwG5lPYNTMdrbUWVfQOP3XjkdU=";
    };
    vendorHash = "sha256-GQaIfUtM3iDQ9jmrSMqYvcPysigdu7w10xGDIYv4OY8=";
  };
  lyricx = {
    pname = "lyricx";
    version = "1.6.4";
    src = fetchurl {
      url = "https://github.com/go-musicfox/LyricsX/releases/download/v1.6.4/LyricsX_1.6.4.zip";
      sha256 = "sha256-xEj0jin2aLQlOcPVITmL14ZVLGKAm1wZf8f4FuLmVB0=";
    };
  };
  maple-mono = {
    pname = "maple-mono";
    version = "6.4";
    src = fetchurl {
      url = "https://github.com/subframe7536/maple-font/releases/download/v6.4/MapleMono-ttf.zip";
      sha256 = "sha256-a06JLIP5aVb9SeEz6kw+LqKy0ydCgaUlPDFWA2Y0G8Q=";
    };
  };
  maple-sc-nf = {
    pname = "maple-sc-nf";
    version = "6.4";
    src = fetchurl {
      url = "https://github.com/subframe7536/Maple-font/releases/download/v6.4/MapleMono-SC-NF.zip";
      sha256 = "sha256-SbXWkrpLJUrq+Jt1h3GBP9md5TbYpPchdiR0oEDMAgY=";
    };
  };
  mihomo = {
    pname = "mihomo";
    version = "v1.18.0";
    src = fetchFromGitHub {
      owner = "MetaCubeX";
      repo = "mihomo";
      rev = "v1.18.0";
      fetchSubmodules = false;
      sha256 = "sha256-lxiPrFPOPNppxdm2Ns4jaMHMRCYFlMz2h2rf7x0gv9c=";
    };
    vendorHash = "sha256-b7q0e3HHolVhwNJF0kwvwuVy8ndJLc0ITMl+0/YtSjA=";
  };
  musicdl = {
    pname = "musicdl";
    version = "ae213b2e5867fa12a6fa2789e24ea792aab38540";
    src = fetchFromGitHub {
      owner = "CharlesPikachu";
      repo = "musicdl";
      rev = "ae213b2e5867fa12a6fa2789e24ea792aab38540";
      fetchSubmodules = false;
      sha256 = "sha256-AoMtlyRiceDzNXKz1K/EH5+/yU2B+UlEso5kjL5ojlI=";
    };
    date = "2023-02-22";
  };
  musicn = {
    pname = "musicn";
    version = "v1.5.0";
    src = fetchFromGitHub {
      owner = "zonemeen";
      repo = "musicn";
      rev = "v1.5.0";
      fetchSubmodules = false;
      sha256 = "sha256-jnS3NwxguAu4SJNFTvk6HgYF0eVw8/L7qC4o1K+WVwE=";
    };
    npmDepsHash = "sha256-Yr0zgQBP/ocJ/ThbFhidPnkP4C8/lWufxkd3sJnqErA=";
  };
  neovide = {
    pname = "neovide";
    version = "0.12.2";
    src = fetchurl {
      url = "https://github.com/neovide/neovide/releases/download/0.12.2/neovide.dmg.zip";
      sha256 = "sha256-cCLswmyKXMwG0RTJWMFFcgdfWyaU9saTgrsZwJuFA1A=";
    };
  };
  next-chat = {
    pname = "next-chat";
    version = "2.10.1";
    src = fetchurl {
      url = "https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/releases/download/v2.10.1/NextChat_2.10.1_x64.dmg";
      sha256 = "sha256-gzVnA+ODxfi1aT2A4Jnofkwa9xYmMYuCTyKng9/CBpw=";
    };
  };
  pngpaste = {
    pname = "pngpaste";
    version = "0.2.3";
    src = fetchFromGitHub {
      owner = "jcsalterego";
      repo = "pngpaste";
      rev = "0.2.3";
      fetchSubmodules = false;
      sha256 = "sha256-uvajxSelk1Wfd5is5kmT2fzDShlufBgC0PDCeabEOSE=";
    };
  };
  qutebrowser = {
    pname = "qutebrowser";
    version = "3.1.0";
    src = fetchurl {
      url = "https://github.com/qutebrowser/qutebrowser/releases/download/v3.1.0/qutebrowser-3.1.0.dmg";
      sha256 = "sha256-AvuuwUnxMcr2ekZ/O1FL/4IizV1aTMhXNrbf1SwNY7U=";
    };
  };
  ryujinx = {
    pname = "ryujinx";
    version = "1.1.1155";
    src = fetchurl {
      url = "https://github.com/Ryujinx/release-channel-master/releases/download/1.1.1155/test-ava-ryujinx-1.1.1155-macos_universal.app.tar.gz";
      sha256 = "sha256-WDiYP0pE3d64SKj159DGntTdCxmjY1wENwUtusa7c2I=";
    };
  };
  ryusak = {
    pname = "ryusak";
    version = "1.6.3";
    src = fetchurl {
      url = "https://github.com/FennyFatal/RyuSAK/releases/download/v1.6.3-experimental/RyuSAK-darwin-arm64-1.6.3.zip";
      sha256 = "sha256-iohH/P56qaFnrS/WhoNxZr66h8cdwCuFfCUDfHF1tho=";
    };
  };
  seam = {
    pname = "seam";
    version = "v_cli.0.1.39";
    src = fetchFromGitHub {
      owner = "Borber";
      repo = "seam";
      rev = "v_cli.0.1.39";
      fetchSubmodules = false;
      sha256 = "sha256-rWbswgVQNA006gi9G+Vma+y0NbMDC0/P6SqHwxxvky8=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./seam-v_cli.0.1.39/Cargo.lock;
      outputHashes = {
        
      };
    };
  };
  sidebery = {
    pname = "sidebery";
    version = "v5.1.1";
    src = fetchFromGitHub {
      owner = "mbnuqw";
      repo = "sidebery";
      rev = "v5.1.1";
      fetchSubmodules = false;
      sha256 = "sha256-zK1kZeI6eyO3z+LyRQuvEncO1kx31UvNK1RrzwYWxWA=";
    };
  };
  spotube = {
    pname = "spotube";
    version = "3.4.1";
    src = fetchurl {
      url = "https://github.com/KRTirtho/spotube/releases/download/v3.4.1/Spotube-macos-universal.dmg";
      sha256 = "sha256-VobLCxsmE5kGIlDDa3v5xIHkw2x2YV14fgHHcDb+bLo=";
    };
  };
  ublock-origin = {
    pname = "ublock-origin";
    version = "1.55.1b28";
    src = fetchurl {
      url = "https://github.com/gorhill/uBlock/releases/download/1.55.1b28/uBlock0_1.55.1b28.firefox.signed.xpi";
      sha256 = "sha256-QHVcVymrQ3MxfOJr+skZrWEM9A+CliiyL7xIQskwdGY=";
    };
  };
  upic = {
    pname = "upic";
    version = "0.21.1";
    src = fetchurl {
      url = "https://github.com/gee1k/uPic/releases/download/v0.21.1/uPic.zip";
      sha256 = "sha256-EVLi85lcwz0W12Q0hhinCp+wZ/Kxf1SKgTZGgJqhFUw=";
    };
  };
  vivaldi = {
    pname = "vivaldi";
    version = "6.5.3206.59";
    src = fetchurl {
      url = "https://downloads.vivaldi.com/stable/Vivaldi.6.5.3206.59.universal.dmg";
      sha256 = "sha256-2ldrznH6krKcwgEHyI/wNGQsVoqxPmcC3a68XJTQiRk=";
    };
  };
  websocket-bridge-python = {
    pname = "websocket-bridge-python";
    version = "0.0.2";
    src = fetchurl {
      url = "https://pypi.org/packages/source/w/websocket_bridge_python/websocket_bridge_python-0.0.2.tar.gz";
      sha256 = "sha256-J9HGD3PSavZQwh2eZPbM6isdknZ1M2nkL5WHlYjRju8=";
    };
  };
  xbydriver = {
    pname = "xbydriver";
    version = "3.24.12922";
    src = fetchurl {
      url = "https://github.com/odomu/aliyunpan/releases/download/v3.24.12922/alixby-3.24.12922-mac-arm64.dmg";
      sha256 = "sha256-TZt3ufH5L7l3WE0/ZNDt82pYKS3GnV436m0i9kcgnxc=";
    };
  };
  yabai-zsh-completions = {
    pname = "yabai-zsh-completions";
    version = "6e38681a002e13bdcd43f461f73c53b7c11fd4e5";
    src = fetchFromGitHub {
      owner = "Amar1729";
      repo = "yabai-zsh-completions";
      rev = "6e38681a002e13bdcd43f461f73c53b7c11fd4e5";
      fetchSubmodules = false;
      sha256 = "sha256-II00E32Pnt7PO+PcTtWp4NzSUDhQJTgAPw9HdlItbhQ=";
    };
    date = "2023-11-13";
  };
  yutto = {
    pname = "yutto";
    version = "v2.0.0-beta.34";
    src = fetchFromGitHub {
      owner = "yutto-dev";
      repo = "yutto";
      rev = "v2.0.0-beta.34";
      fetchSubmodules = false;
      sha256 = "sha256-laliYsrcnvYSvpYRH4IgTGuJxEdx92Lb1urB02ozfaY=";
    };
  };
  zy-player = {
    pname = "zy-player";
    version = "3.3.1";
    src = fetchurl {
      url = "https://github.com/Hiram-Wong/ZyPlayer/releases/download/v3.3.1/zyplayer-mac-3.3.1-arm64.dmg";
      sha256 = "sha256-/43maclqJu75goMBzT8QaqQAqfruHRSE1yYYiWhu8eg=";
    };
  };
}
