# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  about-time = {
    pname = "about-time";
    version = "4.2.1";
    src = fetchurl {
      url = "https://pypi.org/packages/source/a/about-time/about-time-4.2.1.tar.gz";
      sha256 = "sha256-alOIYtM85n2ZdCnRSZgxDh2/2my32bv795nEcJhH/s4=";
    };
  };
  aerospace = {
    pname = "aerospace";
    version = "0.8.7-Beta";
    src = fetchurl {
      url = "https://github.com/nikitabobko/AeroSpace/releases/download/v0.8.7-Beta/AeroSpace-v0.8.7-Beta.zip";
      sha256 = "sha256-/zzkLIcT1sy2aWPa/Od/16ZdpgxV2w2Blt2rB2mC890=";
    };
  };
  alist = {
    pname = "alist";
    version = "v3.32.0";
    src = fetchFromGitHub {
      owner = "alist-org";
      repo = "alist";
      rev = "v3.32.0";
      fetchSubmodules = false;
      sha256 = "sha256-SHiPaXIcjMwAb+GLnVvmAkPK4Wv/3mh3AbIGjQMX0qQ=";
    };
    vendorHash = "sha256-AIgT1USS1uWMTWYYc7uUORn5pVsbGynGV3KjiGmvU1Y=";
  };
  alist-web = {
    pname = "alist-web";
    version = "3.32.0";
    src = fetchurl {
      url = "https://github.com/alist-org/alist-web/releases/download/3.32.0/dist.tar.gz";
      sha256 = "sha256-KvklBz5SH/rdmYZrZb5U1JWk3OC0FkRpECMM2DtLEh8=";
    };
  };
  alive-progress = {
    pname = "alive-progress";
    version = "3.1.5";
    src = fetchurl {
      url = "https://pypi.org/packages/source/a/alive-progress/alive-progress-3.1.5.tar.gz";
      sha256 = "sha256-QuOZpmyBUNxQdgLf97eVPxBe8R+vl92qbSexy/RcTJg=";
    };
  };
  bbdown = {
    pname = "bbdown";
    version = "1196918e709f883eabfe3122ccad824b8f551381";
    src = fetchFromGitHub {
      owner = "nilaoda";
      repo = "BBDown";
      rev = "1196918e709f883eabfe3122ccad824b8f551381";
      fetchSubmodules = false;
      sha256 = "sha256-foTgCQKzYZc4aDxiAeoXR4jdEytqnkCt1Rwr2ztostM=";
    };
    date = "2023-11-13";
  };
  calibre = {
    pname = "calibre";
    version = "7.6.0";
    src = fetchurl {
      url = "https://download.calibre-ebook.com/7.6.0/calibre-7.6.0.dmg";
      sha256 = "sha256-p9bqym47j/YrNV2hzIl3YtUqwUih4c42pu61kAayQMs=";
    };
  };
  calibrepath = {
    pname = "calibrepath";
    version = "7.6.0";
    src = fetchurl {
      url = "https://github.com/Cirn09/calibre-do-not-translate-my-path/releases/download/v7.6.0/mac-patch-backend+update-v7.6.0.zip";
      sha256 = "sha256-P4G4BrZepXNHsCzKB9Vkv0AsPAov6DvaKNAieulaKfc=";
    };
  };
  chatgpt = {
    pname = "chatgpt";
    version = "1.1.0";
    src = fetchurl {
      url = "https://github.com/lencx/ChatGPT/releases/download/v1.1.0/ChatGPT_1.1.0_macos_aarch64.dmg";
      sha256 = "sha256-+HC6E1rZkHFUdMuwOLWzisuNCGQIA+LHnIeOIQ9IAPY=";
    };
  };
  "chrome.arm64" = {
    pname = "chrome.arm64";
    version = "122.0.6261.94";
    src = fetchurl {
      url = "https://registry.npmmirror.com/-/binary/chrome-for-testing/122.0.6261.94/mac-arm64/chrome-mac-arm64.zip";
      sha256 = "sha256-jefQbQ2O9if7fhBDU8kngrU1BhFWDKBzizqhq+iS9Xs=";
    };
  };
  "chrome.x64" = {
    pname = "chrome.x64";
    version = "122.0.6261.94";
    src = fetchurl {
      url = "https://registry.npmmirror.com/-/binary/chrome-for-testing/122.0.6261.94/mac-x64/chrome-mac-x64.zip";
      sha256 = "sha256-YuzV4UG+8CjNlc3jTI8vy5pZKMM/x/I8R+f8MR5WoRs=";
    };
  };
  "chromium.arm64" = {
    pname = "chromium.arm64";
    version = "122.0.6261.69-1.1";
    src = fetchurl {
      url = "https://github.com/ungoogled-software/ungoogled-chromium-macos/releases/download/122.0.6261.69-1.1/ungoogled-chromium_122.0.6261.69-1.1_arm64-macos.dmg";
      sha256 = "sha256-3YGBexErHFbVKYnmcUXW87Q0TVFeQQjSienrinEQLE8=";
    };
  };
  "chromium.x64" = {
    pname = "chromium.x64";
    version = "122.0.6261.69-1.1";
    src = fetchurl {
      url = "https://github.com/ungoogled-software/ungoogled-chromium-macos/releases/download/122.0.6261.69-1.1/ungoogled-chromium_122.0.6261.69-1.1_x86-64-macos.dmg";
      sha256 = "sha256-uk2Yb0J4RxBW/9dbq6MOlft43YLDTLmznnQibmpYi/8=";
    };
  };
  clash-nyanpasu = {
    pname = "clash-nyanpasu";
    version = "1.4.5";
    src = fetchurl {
      url = "https://github.com/keiko233/clash-nyanpasu/releases/download/v1.4.5/Clash.Nyanpasu_1.4.5_aarch64.dmg";
      sha256 = "sha256-shBqYYBPSgfeFK+QQOEBCQLcqtEplTHxnbpPk7djJBM=";
    };
  };
  clash-verge = {
    pname = "clash-verge";
    version = "1.3.8";
    src = fetchurl {
      url = "https://github.com/zzzgydi/clash-verge/releases/download/v1.3.8/Clash.Verge_1.3.8_aarch64.dmg";
      sha256 = "sha256-/YNwMjppWogo0adIfJ50IAzja1GzJElb+6IUmMb8jEg=";
    };
  };
  clash2singbox = {
    pname = "clash2singbox";
    version = "v0.1.4";
    src = fetchFromGitHub {
      owner = "xmdhs";
      repo = "clash2singbox";
      rev = "v0.1.4";
      fetchSubmodules = false;
      sha256 = "sha256-qEv5lmuu4UWaxmCQ0sb21TMJVhYaW7VscD6O+dOWjgE=";
    };
    vendorHash = "sha256-+trt7BLgy1d1ENrqf/J0mf8ECnKfYl3P/KibQQxNRN4=";
  };
  darkreader = {
    pname = "darkreader";
    version = "4.9.78";
    src = fetchurl {
      url = "https://github.com/darkreader/darkreader/releases/download/v4.9.78/darkreader-firefox.xpi";
      sha256 = "sha256-m2uJ5BBpCubDFDd1ohVGPfLorA1IYaca+2XhZaG7n6o=";
    };
  };
  deeplx = {
    pname = "deeplx";
    version = "v0.8.8";
    src = fetchFromGitHub {
      owner = "OwO-Network";
      repo = "DeepLX";
      rev = "v0.8.8";
      fetchSubmodules = false;
      sha256 = "sha256-4/sfePuNS67tlyt0KGqLiYXfTu5uvHS2+XD8X5IrROo=";
    };
    vendorHash = "sha256-x4Z8fTrgXOH+9Ixj9NKr2G3BuQPm7/CqNGoIVbXmMOE=";
  };
  dict2xml = {
    pname = "dict2xml";
    version = "release-1.7.5";
    src = fetchFromGitHub {
      owner = "delfick";
      repo = "python-dict2xml";
      rev = "release-1.7.5";
      fetchSubmodules = false;
      sha256 = "sha256-GNvG1VFz/qkkTrKleMrq8n6kcIYtfhUlQMyCqH9uQzw=";
    };
  };
  downkyi = {
    pname = "downkyi";
    version = "1.0.7";
    src = fetchurl {
      url = "https://github.com/yaobiao131/downkyicore/releases/download/v1.0.7/DownKyi-1.0.7-osx-arm64.dmg";
      sha256 = "sha256-6VqAUQ+JzL5Xq7xmXqgq+UU2/If6nA+xgyzx4d5kaDM=";
    };
  };
  dutis = {
    pname = "dutis";
    version = "e8f8d6176fff1b42e7e68a552fcfd2923f9c27a2";
    src = fetchFromGitHub {
      owner = "tsonglew";
      repo = "dutis";
      rev = "e8f8d6176fff1b42e7e68a552fcfd2923f9c27a2";
      fetchSubmodules = false;
      sha256 = "sha256-mwIBWLKUbqINPc1SnsMHVaN+5sXlRvC20M6kv9DAa5I=";
    };
    vendorHash = "sha256-lUBSQq4ac/Vc76gmSaKFkfCrO/BmhQU+3UyA+URb8l8=";
    date = "2023-09-27";
  };
  "emacs29.no-frame-refocus-cocoa" = {
    pname = "emacs29.no-frame-refocus-cocoa";
    version = "d5dd64d3ad95b5e99c282f8cb7c596ed69da108b";
    src = fetchurl {
      url = "https://github.com/d12frosted/homebrew-emacs-plus/raw/d5dd64d3ad95b5e99c282f8cb7c596ed69da108b/patches/emacs-28/no-frame-refocus-cocoa.patch";
      sha256 = "sha256-+1d33IkKoHNJ8UOuZcK89D7a1v6/1WSwGiI1xaFfyr0=";
    };
    date = "2024-02-21";
  };
  "emacs29.poll" = {
    pname = "emacs29.poll";
    version = "d5dd64d3ad95b5e99c282f8cb7c596ed69da108b";
    src = fetchurl {
      url = "https://github.com/d12frosted/homebrew-emacs-plus/raw/d5dd64d3ad95b5e99c282f8cb7c596ed69da108b/patches/emacs-29/poll.patch";
      sha256 = "sha256-BS6srFt72GtGb5o9GL/5NX8rl1F/RjoJ5MUSVb2xRkg=";
    };
    date = "2024-02-21";
  };
  "emacs29.role-patch" = {
    pname = "emacs29.role-patch";
    version = "d5dd64d3ad95b5e99c282f8cb7c596ed69da108b";
    src = fetchurl {
      url = "https://github.com/d12frosted/homebrew-emacs-plus/raw/d5dd64d3ad95b5e99c282f8cb7c596ed69da108b/patches/emacs-28/fix-window-role.patch";
      sha256 = "sha256-H4Qj6n5uZsmsbdjjexGZctqhJk3gAXKiSnmnEO/LgTA=";
    };
    date = "2024-02-21";
  };
  "emacs29.round-undecorated-frame" = {
    pname = "emacs29.round-undecorated-frame";
    version = "d5dd64d3ad95b5e99c282f8cb7c596ed69da108b";
    src = fetchurl {
      url = "https://github.com/d12frosted/homebrew-emacs-plus/raw/d5dd64d3ad95b5e99c282f8cb7c596ed69da108b/patches/emacs-29/round-undecorated-frame.patch";
      sha256 = "sha256-dFH4D1WYQOVOagUuVdEQB3irxV+Y8dDAOKJOJXc/KHQ=";
    };
    date = "2024-02-21";
  };
  "emacs29.system-appearance" = {
    pname = "emacs29.system-appearance";
    version = "d5dd64d3ad95b5e99c282f8cb7c596ed69da108b";
    src = fetchurl {
      url = "https://github.com/d12frosted/homebrew-emacs-plus/raw/d5dd64d3ad95b5e99c282f8cb7c596ed69da108b/patches/emacs-28/system-appearance.patch";
      sha256 = "sha256-1u4VmDmzi2r1Ode5vf8jEmPkUcH9Qu7A0SUxjJ24zZI=";
    };
    date = "2024-02-21";
  };
  emacsclient = {
    pname = "emacsclient";
    version = "917f2f2694019d534098f5e2e365b5f6e5ddbd37";
    src = fetchurl {
      url = "https://github.com/nashamri/spacemacs-logo/raw/917f2f2694019d534098f5e2e365b5f6e5ddbd37/spacemacs.icns";
      sha256 = "sha256-s9uLfPpLxbziS8TcHt47dSxxhse1TAmZTqtexOqkiQA=";
    };
    date = "2018-08-26";
  };
  fav = {
    pname = "fav";
    version = "v0.2.6";
    src = fetchFromGitHub {
      owner = "kingwingfly";
      repo = "fav";
      rev = "v0.2.6";
      fetchSubmodules = false;
      sha256 = "sha256-L4yJfgJNxlWTXyL7i6UiDfbjpzXhp8pxTLrd/SSzp9A=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./fav-v0.2.6/Cargo.lock;
      outputHashes = {
        
      };
    };
  };
  firefox-utils = {
    pname = "firefox-utils";
    version = "b013243f1916576166a02d816651c2cc6416f63e";
    src = fetchurl {
      url = "https://github.com/xiaoxiaoflood/firefox-scripts/raw/b013243f1916576166a02d816651c2cc6416f63e/utils.zip";
      sha256 = "sha256-2LK3BGKSsFeMKLsXnMNz2ONJ/Wb07VTLSu4TwemYNOQ=";
    };
    date = "2023-02-24";
  };
  fx-folder = {
    pname = "fx-folder";
    version = "b013243f1916576166a02d816651c2cc6416f63e";
    src = fetchurl {
      url = "https://github.com/xiaoxiaoflood/firefox-scripts/raw/b013243f1916576166a02d816651c2cc6416f63e/fx-folder.zip";
      sha256 = "sha256-IAiHzJ/9YBuChVTePMmXFYtx69jX+crDe1GcAcfZ+OI=";
    };
    date = "2023-02-24";
  };
  go-musicfox = {
    pname = "go-musicfox";
    version = "v4.3.1";
    src = fetchFromGitHub {
      owner = "go-musicfox";
      repo = "go-musicfox";
      rev = "v4.3.1";
      fetchSubmodules = false;
      sha256 = "sha256-QZHuQAOnthSm7Kb82i3NUWTnKk+9OMHV5vzOU72inX0=";
    };
  };
  httpx = {
    pname = "httpx";
    version = "0.27.0";
    src = fetchFromGitHub {
      owner = "encode";
      repo = "httpx";
      rev = "0.27.0";
      fetchSubmodules = false;
      sha256 = "sha256-13EnSzrCkseK6s6Yz9OpLzqo/2PTFiB31m5fAIJLoZg=";
    };
  };
  iina = {
    pname = "iina";
    version = "1.3.4";
    src = fetchurl {
      url = "https://github.com/iina/iina/releases/download/v1.3.4/IINA.v1.3.4.dmg";
      sha256 = "sha256-feUPWtSi/Vsnv1mjGyBgB0wFMxx6r6UzrUratlAo14w=";
    };
  };
  iinaplus = {
    pname = "iinaplus";
    version = "0.7.22";
    src = fetchurl {
      url = "https://github.com/xjbeta/iina-plus/releases/download/0.7.22/IINA+.0.7.22.dmg";
      sha256 = "sha256-s7CE9g7llVCOLwT4HiVOMdshmWc5sOpFoee6D91Gj5w=";
    };
  };
  lazyvim-star = {
    pname = "lazyvim-star";
    version = "741ff3aa70336abb6c76ee4c49815ae589a1b852";
    src = fetchFromGitHub {
      owner = "LazyVim";
      repo = "starter";
      rev = "741ff3aa70336abb6c76ee4c49815ae589a1b852";
      fetchSubmodules = false;
      sha256 = "sha256-EkDWEwXTqQIIRWmnqBMVBZ970QBbPmBW6X7n7xzYmzc=";
    };
    date = "2024-01-19";
  };
  localsend = {
    pname = "localsend";
    version = "1.14.0";
    src = fetchurl {
      url = "https://github.com/localsend/localsend/releases/download/v1.14.0/LocalSend-1.14.0.dmg";
      sha256 = "sha256-L7V48QoOA0cjx45n+9Xav/zzCzCsZB3TBip0WGusMXg=";
    };
  };
  lporg = {
    pname = "lporg";
    version = "v20.4.31";
    src = fetchFromGitHub {
      owner = "blacktop";
      repo = "lporg";
      rev = "v20.4.31";
      fetchSubmodules = false;
      sha256 = "sha256-A/OE67qAn9RHSCveiRwG5lPYNTMdrbUWVfQOP3XjkdU=";
    };
    vendorHash = "sha256-GQaIfUtM3iDQ9jmrSMqYvcPysigdu7w10xGDIYv4OY8=";
  };
  lyricx = {
    pname = "lyricx";
    version = "1.6.4";
    src = fetchurl {
      url = "https://github.com/go-musicfox/LyricsX/releases/download/v1.6.4/LyricsX_1.6.4.zip";
      sha256 = "sha256-xEj0jin2aLQlOcPVITmL14ZVLGKAm1wZf8f4FuLmVB0=";
    };
  };
  maple-mono = {
    pname = "maple-mono";
    version = "6.4";
    src = fetchurl {
      url = "https://github.com/subframe7536/maple-font/releases/download/v6.4/MapleMono-ttf.zip";
      sha256 = "sha256-a06JLIP5aVb9SeEz6kw+LqKy0ydCgaUlPDFWA2Y0G8Q=";
    };
  };
  maple-sc-nf = {
    pname = "maple-sc-nf";
    version = "6.4";
    src = fetchurl {
      url = "https://github.com/subframe7536/Maple-font/releases/download/v6.4/MapleMono-SC-NF.zip";
      sha256 = "sha256-SbXWkrpLJUrq+Jt1h3GBP9md5TbYpPchdiR0oEDMAgY=";
    };
  };
  mihomo = {
    pname = "mihomo";
    version = "v1.18.1";
    src = fetchFromGitHub {
      owner = "MetaCubeX";
      repo = "mihomo";
      rev = "v1.18.1";
      fetchSubmodules = false;
      sha256 = "sha256-ezOkDrpytZQdc+Txe4eUyuWY6oipn9jIrmu7aO8lNlQ=";
    };
    vendorHash = "sha256-tvPR5kAta4MlMTwjfxwVOacRr2nVpfalbN08mfxml64=";
  };
  musicdl = {
    pname = "musicdl";
    version = "ae213b2e5867fa12a6fa2789e24ea792aab38540";
    src = fetchFromGitHub {
      owner = "CharlesPikachu";
      repo = "musicdl";
      rev = "ae213b2e5867fa12a6fa2789e24ea792aab38540";
      fetchSubmodules = false;
      sha256 = "sha256-AoMtlyRiceDzNXKz1K/EH5+/yU2B+UlEso5kjL5ojlI=";
    };
    date = "2023-02-22";
  };
  musicn = {
    pname = "musicn";
    version = "v1.5.0";
    src = fetchFromGitHub {
      owner = "zonemeen";
      repo = "musicn";
      rev = "v1.5.0";
      fetchSubmodules = false;
      sha256 = "sha256-jnS3NwxguAu4SJNFTvk6HgYF0eVw8/L7qC4o1K+WVwE=";
    };
    npmDepsHash = "sha256-Yr0zgQBP/ocJ/ThbFhidPnkP4C8/lWufxkd3sJnqErA=";
  };
  neovide = {
    pname = "neovide";
    version = "0.12.2";
    src = fetchurl {
      url = "https://github.com/neovide/neovide/releases/download/0.12.2/neovide.dmg.zip";
      sha256 = "sha256-cCLswmyKXMwG0RTJWMFFcgdfWyaU9saTgrsZwJuFA1A=";
    };
  };
  next-chat = {
    pname = "next-chat";
    version = "2.11.2";
    src = fetchurl {
      url = "https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/releases/download/v2.11.2/NextChat_2.11.2_universal.dmg";
      sha256 = "sha256-PEOm2y7CbxP2kpVhujKIb1Y8pC0nV7pQKrSn3/fC874=";
    };
  };
  pngpaste = {
    pname = "pngpaste";
    version = "0.2.3";
    src = fetchFromGitHub {
      owner = "jcsalterego";
      repo = "pngpaste";
      rev = "0.2.3";
      fetchSubmodules = false;
      sha256 = "sha256-uvajxSelk1Wfd5is5kmT2fzDShlufBgC0PDCeabEOSE=";
    };
  };
  qbittorrent = {
    pname = "qbittorrent";
    version = "release-4.6.3.10";
    src = fetchFromGitHub {
      owner = "c0re100";
      repo = "qBittorrent-Enhanced-Edition";
      rev = "release-4.6.3.10";
      fetchSubmodules = false;
      sha256 = "sha256-O25sJmpyOwhtjrCbN4srKjcNDxEPHwX08MY+AM8QaCU=";
    };
  };
  qutebrowser = {
    pname = "qutebrowser";
    version = "3.1.0";
    src = fetchurl {
      url = "https://github.com/qutebrowser/qutebrowser/releases/download/v3.1.0/qutebrowser-3.1.0.dmg";
      sha256 = "sha256-AvuuwUnxMcr2ekZ/O1FL/4IizV1aTMhXNrbf1SwNY7U=";
    };
  };
  ryujinx = {
    pname = "ryujinx";
    version = "1.1.1214";
    src = fetchurl {
      url = "https://github.com/Ryujinx/release-channel-master/releases/download/1.1.1214/test-ava-ryujinx-1.1.1214-macos_universal.app.tar.gz";
      sha256 = "sha256-9cnJPrp4NKsBWQ3szqOCtqg4ZcZeBnzJ+eFi/ZHL3fw=";
    };
  };
  ryusak = {
    pname = "ryusak";
    version = "1.6.3";
    src = fetchurl {
      url = "https://github.com/FennyFatal/RyuSAK/releases/download/v1.6.3-experimental/RyuSAK-darwin-arm64-1.6.3.zip";
      sha256 = "sha256-iohH/P56qaFnrS/WhoNxZr66h8cdwCuFfCUDfHF1tho=";
    };
  };
  seam = {
    pname = "seam";
    version = "v_cli.0.1.39";
    src = fetchFromGitHub {
      owner = "Borber";
      repo = "seam";
      rev = "v_cli.0.1.39";
      fetchSubmodules = false;
      sha256 = "sha256-rWbswgVQNA006gi9G+Vma+y0NbMDC0/P6SqHwxxvky8=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./seam-v_cli.0.1.39/Cargo.lock;
      outputHashes = {
        
      };
    };
  };
  sidebery = {
    pname = "sidebery";
    version = "v5.1.1";
    src = fetchFromGitHub {
      owner = "mbnuqw";
      repo = "sidebery";
      rev = "v5.1.1";
      fetchSubmodules = false;
      sha256 = "sha256-zK1kZeI6eyO3z+LyRQuvEncO1kx31UvNK1RrzwYWxWA=";
    };
  };
  spotube = {
    pname = "spotube";
    version = "3.4.1";
    src = fetchurl {
      url = "https://github.com/KRTirtho/spotube/releases/download/v3.4.1/Spotube-macos-universal.dmg";
      sha256 = "sha256-VobLCxsmE5kGIlDDa3v5xIHkw2x2YV14fgHHcDb+bLo=";
    };
  };
  switchaudio-osx = {
    pname = "switchaudio-osx";
    version = "1.2.2";
    src = fetchFromGitHub {
      owner = "deweller";
      repo = "switchaudio-osx";
      rev = "1.2.2";
      fetchSubmodules = false;
      sha256 = "sha256-AZJn5kHK/al94ONfIHcG+W0jyMfgdJkIngN+PVj+I44=";
    };
  };
  ublock-origin = {
    pname = "ublock-origin";
    version = "1.56.1b10";
    src = fetchurl {
      url = "https://github.com/gorhill/uBlock/releases/download/1.56.1b10/uBlock0_1.56.1b10.firefox.signed.xpi";
      sha256 = "sha256-/Ta34QNxDR51IILYwLKDFZgKRPb1jRQiQUKAeG2sHL4=";
    };
  };
  upic = {
    pname = "upic";
    version = "0.21.1";
    src = fetchurl {
      url = "https://github.com/gee1k/uPic/releases/download/v0.21.1/uPic.zip";
      sha256 = "sha256-EVLi85lcwz0W12Q0hhinCp+wZ/Kxf1SKgTZGgJqhFUw=";
    };
  };
  vivaldi = {
    pname = "vivaldi";
    version = "6.6.3271.45";
    src = fetchurl {
      url = "https://downloads.vivaldi.com/stable/Vivaldi.6.6.3271.45.universal.dmg";
      sha256 = "sha256-bbwN72Hdc1UTssVJ5SVqoQpmQf8dxWiPSS0j5zK/u/Q=";
    };
  };
  websocket-bridge-python = {
    pname = "websocket-bridge-python";
    version = "0.0.2";
    src = fetchurl {
      url = "https://pypi.org/packages/source/w/websocket_bridge_python/websocket_bridge_python-0.0.2.tar.gz";
      sha256 = "sha256-J9HGD3PSavZQwh2eZPbM6isdknZ1M2nkL5WHlYjRju8=";
    };
  };
  xbydriver = {
    pname = "xbydriver";
    version = "3.24.30216";
    src = fetchurl {
      url = "https://github.com/odomu/aliyunpan/releases/download/v3.24.30216/alixby-3.24.30216-mac-arm64.dmg";
      sha256 = "sha256-8Dd28LMAs2YiXgmSTmRKuwP2D+Dyvfuy+ZHi1mzRcJ8=";
    };
  };
  yabai = {
    pname = "yabai";
    version = "v6.0.15";
    src = fetchFromGitHub {
      owner = "koekeishiya";
      repo = "yabai";
      rev = "v6.0.15";
      fetchSubmodules = false;
      sha256 = "sha256-buX6FRIXdM5VmYpA80eESDMPf+xeMfJJj0ulyx2g94M=";
    };
  };
  yabai-zsh-completions = {
    pname = "yabai-zsh-completions";
    version = "6e38681a002e13bdcd43f461f73c53b7c11fd4e5";
    src = fetchFromGitHub {
      owner = "Amar1729";
      repo = "yabai-zsh-completions";
      rev = "6e38681a002e13bdcd43f461f73c53b7c11fd4e5";
      fetchSubmodules = false;
      sha256 = "sha256-II00E32Pnt7PO+PcTtWp4NzSUDhQJTgAPw9HdlItbhQ=";
    };
    date = "2023-11-13";
  };
  yutto = {
    pname = "yutto";
    version = "v2.0.0-beta.36";
    src = fetchFromGitHub {
      owner = "yutto-dev";
      repo = "yutto";
      rev = "v2.0.0-beta.36";
      fetchSubmodules = false;
      sha256 = "sha256-rXajj7lGuiirWHctePIhChGgD74KxbA0XJ/AIGGW6aM=";
    };
  };
  zy-player = {
    pname = "zy-player";
    version = "3.3.2";
    src = fetchurl {
      url = "https://github.com/Hiram-Wong/ZyPlayer/releases/download/v3.3.2/zyplayer-mac-3.3.2-arm64.dmg";
      sha256 = "sha256-XjK6m5hlFAT84/cEuDn5Q59x1dW1hexM8GyCEkhfaeQ=";
    };
  };
}
