# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  about-time = {
    pname = "about-time";
    version = "4.2.1";
    src = fetchurl {
      url = "https://pypi.org/packages/source/a/about-time/about-time-4.2.1.tar.gz";
      sha256 = "sha256-alOIYtM85n2ZdCnRSZgxDh2/2my32bv795nEcJhH/s4=";
    };
  };
  aerospace = {
    pname = "aerospace";
    version = "0.9.2-Beta";
    src = fetchurl {
      url = "https://github.com/nikitabobko/AeroSpace/releases/download/v0.9.2-Beta/AeroSpace-v0.9.2-Beta.zip";
      sha256 = "sha256-ASZfCv9MRyme1+Qx3J+ucOdFXlusWx108hRCKnkjr2c=";
    };
  };
  alist = {
    pname = "alist";
    version = "v3.33.0";
    src = fetchFromGitHub {
      owner = "alist-org";
      repo = "alist";
      rev = "v3.33.0";
      fetchSubmodules = false;
      sha256 = "sha256-/Os8DndNtWvwIHQ1us7TPg16+WOpMFcntZv9wv4O1fU=";
    };
    vendorHash = "sha256-dr6fiCVihZpDN1ilKCsFW6LS8OnZJC6VwvIEyoZ1S5s=";
  };
  alist-web = {
    pname = "alist-web";
    version = "3.33.0";
    src = fetchurl {
      url = "https://github.com/alist-org/alist-web/releases/download/3.33.0/dist.tar.gz";
      sha256 = "sha256-UK4FOXILznxHCsa8RyFrDhA+c2Nu46m0uTZOK1LKk/Y=";
    };
  };
  alive-progress = {
    pname = "alive-progress";
    version = "3.1.5";
    src = fetchurl {
      url = "https://pypi.org/packages/source/a/alive-progress/alive-progress-3.1.5.tar.gz";
      sha256 = "sha256-QuOZpmyBUNxQdgLf97eVPxBe8R+vl92qbSexy/RcTJg=";
    };
  };
  bbdown = {
    pname = "bbdown";
    version = "1196918e709f883eabfe3122ccad824b8f551381";
    src = fetchFromGitHub {
      owner = "nilaoda";
      repo = "BBDown";
      rev = "1196918e709f883eabfe3122ccad824b8f551381";
      fetchSubmodules = false;
      sha256 = "sha256-foTgCQKzYZc4aDxiAeoXR4jdEytqnkCt1Rwr2ztostM=";
    };
    date = "2023-11-13";
  };
  calibre = {
    pname = "calibre";
    version = "7.8.0";
    src = fetchurl {
      url = "https://download.calibre-ebook.com/7.8.0/calibre-7.8.0.dmg";
      sha256 = "sha256-ugA+ekCx/fyIeb11DTDumC4iREkhgz2Wcs14P+TMSe4=";
    };
  };
  calibrepath = {
    pname = "calibrepath";
    version = "7.8.0";
    src = fetchurl {
      url = "https://github.com/Cirn09/calibre-do-not-translate-my-path/releases/download/v7.8.0/mac-patch-backend+update-v7.8.0.zip";
      sha256 = "sha256-F4Ci5wwmSDQ7U3K/tm5Fz//SEpEAYuL0DgR9YYEba/8=";
    };
  };
  chatgpt = {
    pname = "chatgpt";
    version = "1.1.0";
    src = fetchurl {
      url = "https://github.com/lencx/ChatGPT/releases/download/v1.1.0/ChatGPT_1.1.0_macos_aarch64.dmg";
      sha256 = "sha256-+HC6E1rZkHFUdMuwOLWzisuNCGQIA+LHnIeOIQ9IAPY=";
    };
  };
  "chrome.arm64" = {
    pname = "chrome.arm64";
    version = "123.0.6312.105";
    src = fetchurl {
      url = "https://registry.npmmirror.com/-/binary/chrome-for-testing/123.0.6312.105/mac-arm64/chrome-mac-arm64.zip";
      sha256 = "sha256-RTMaro1h7ws7ObA06yPIh6RlhpAHifIojlSaznYhVDI=";
    };
  };
  "chromium.arm64" = {
    pname = "chromium.arm64";
    version = "123.0.6312.105-1.1";
    src = fetchurl {
      url = "https://github.com/ungoogled-software/ungoogled-chromium-macos/releases/download/123.0.6312.105-1.1/ungoogled-chromium_123.0.6312.105-1.1_arm64-macos.dmg";
      sha256 = "sha256-5S2ig7og3LZWtyHIljrxOH5frUwhS8ib6wxvusQJ5Sg=";
    };
  };
  clash-nyanpasu = {
    pname = "clash-nyanpasu";
    version = "1.5.0";
    src = fetchurl {
      url = "https://github.com/keiko233/clash-nyanpasu/releases/download/v1.5.0/Clash.Nyanpasu_1.5.0_aarch64.dmg";
      sha256 = "sha256-TCJBw9ZDBb0EUeM9kbLhBThrqLu6xndiLbNGEV/JIBU=";
    };
  };
  clash-verge = {
    pname = "clash-verge";
    version = "1.3.8";
    src = fetchurl {
      url = "https://github.com/zzzgydi/clash-verge/releases/download/v1.3.8/Clash.Verge_1.3.8_aarch64.dmg";
      sha256 = "sha256-/YNwMjppWogo0adIfJ50IAzja1GzJElb+6IUmMb8jEg=";
    };
  };
  clash2singbox = {
    pname = "clash2singbox";
    version = "v0.1.4";
    src = fetchFromGitHub {
      owner = "xmdhs";
      repo = "clash2singbox";
      rev = "v0.1.4";
      fetchSubmodules = false;
      sha256 = "sha256-qEv5lmuu4UWaxmCQ0sb21TMJVhYaW7VscD6O+dOWjgE=";
    };
    vendorHash = "sha256-+trt7BLgy1d1ENrqf/J0mf8ECnKfYl3P/KibQQxNRN4=";
  };
  darkreader = {
    pname = "darkreader";
    version = "4.9.82";
    src = fetchurl {
      url = "https://github.com/darkreader/darkreader/releases/download/v4.9.82/darkreader-firefox.xpi";
      sha256 = "sha256-42QjEzJOFmSFos0z4FcMJPxuT0DaayQFyQYRvc+VnWY=";
    };
  };
  deeplx = {
    pname = "deeplx";
    version = "v0.9.1";
    src = fetchFromGitHub {
      owner = "OwO-Network";
      repo = "DeepLX";
      rev = "v0.9.1";
      fetchSubmodules = false;
      sha256 = "sha256-rxzYWxh8BnXxrT0eJVqm6dhYMke/rcQ5/SCIXFGiqis=";
    };
    vendorHash = "sha256-kTSMY4K07hpy/ry5/kxTP3RcR5ewMzj/BDJxxYRdxYI=";
  };
  dict2xml = {
    pname = "dict2xml";
    version = "release-1.7.5";
    src = fetchFromGitHub {
      owner = "delfick";
      repo = "python-dict2xml";
      rev = "release-1.7.5";
      fetchSubmodules = false;
      sha256 = "sha256-GNvG1VFz/qkkTrKleMrq8n6kcIYtfhUlQMyCqH9uQzw=";
    };
  };
  downkyi = {
    pname = "downkyi";
    version = "1.0.8";
    src = fetchurl {
      url = "https://github.com/yaobiao131/downkyicore/releases/download/v1.0.8/DownKyi-1.0.8-osx-arm64.dmg";
      sha256 = "sha256-89dEve0zH4m07K4dK7PHCLSV57pcsaJVEeFMhOoi+eY=";
    };
  };
  dutis = {
    pname = "dutis";
    version = "e1c3f9ba222552350964b51389507ea0be93057c";
    src = fetchFromGitHub {
      owner = "tsonglew";
      repo = "dutis";
      rev = "e1c3f9ba222552350964b51389507ea0be93057c";
      fetchSubmodules = false;
      sha256 = "sha256-hPvQ6M+foEzQEcPYYLGzVJ69moAkfMe9boKQ/2ajFtI=";
    };
    vendorHash = "sha256-lUBSQq4ac/Vc76gmSaKFkfCrO/BmhQU+3UyA+URb8l8=";
    date = "2024-03-20";
  };
  "emacs29.no-frame-refocus-cocoa" = {
    pname = "emacs29.no-frame-refocus-cocoa";
    version = "29";
    src = fetchurl {
      url = "https://github.com/d12frosted/homebrew-emacs-plus/raw/d5dd64d3ad95b5e99c282f8cb7c596ed69da108b/patches/emacs-28/no-frame-refocus-cocoa.patch";
      sha256 = "sha256-+1d33IkKoHNJ8UOuZcK89D7a1v6/1WSwGiI1xaFfyr0=";
    };
  };
  "emacs29.poll" = {
    pname = "emacs29.poll";
    version = "29";
    src = fetchurl {
      url = "https://github.com/d12frosted/homebrew-emacs-plus/raw/d5dd64d3ad95b5e99c282f8cb7c596ed69da108b/patches/emacs-29/poll.patch";
      sha256 = "sha256-BS6srFt72GtGb5o9GL/5NX8rl1F/RjoJ5MUSVb2xRkg=";
    };
  };
  "emacs29.role-patch" = {
    pname = "emacs29.role-patch";
    version = "29";
    src = fetchurl {
      url = "https://github.com/d12frosted/homebrew-emacs-plus/raw/d5dd64d3ad95b5e99c282f8cb7c596ed69da108b/patches/emacs-28/fix-window-role.patch";
      sha256 = "sha256-H4Qj6n5uZsmsbdjjexGZctqhJk3gAXKiSnmnEO/LgTA=";
    };
  };
  "emacs29.round-undecorated-frame" = {
    pname = "emacs29.round-undecorated-frame";
    version = "29";
    src = fetchurl {
      url = "https://github.com/d12frosted/homebrew-emacs-plus/raw/d5dd64d3ad95b5e99c282f8cb7c596ed69da108b/patches/emacs-29/round-undecorated-frame.patch";
      sha256 = "sha256-dFH4D1WYQOVOagUuVdEQB3irxV+Y8dDAOKJOJXc/KHQ=";
    };
  };
  "emacs29.system-appearance" = {
    pname = "emacs29.system-appearance";
    version = "29";
    src = fetchurl {
      url = "https://github.com/d12frosted/homebrew-emacs-plus/raw/d5dd64d3ad95b5e99c282f8cb7c596ed69da108b/patches/emacs-28/system-appearance.patch";
      sha256 = "sha256-1u4VmDmzi2r1Ode5vf8jEmPkUcH9Qu7A0SUxjJ24zZI=";
    };
  };
  emacsclient = {
    pname = "emacsclient";
    version = "917f2f2694019d534098f5e2e365b5f6e5ddbd37";
    src = fetchurl {
      url = "https://github.com/nashamri/spacemacs-logo/raw/917f2f2694019d534098f5e2e365b5f6e5ddbd37/spacemacs.icns";
      sha256 = "sha256-s9uLfPpLxbziS8TcHt47dSxxhse1TAmZTqtexOqkiQA=";
    };
    date = "2018-08-26";
  };
  fav = {
    pname = "fav";
    version = "v0.2.11";
    src = fetchFromGitHub {
      owner = "kingwingfly";
      repo = "fav";
      rev = "v0.2.11";
      fetchSubmodules = false;
      sha256 = "sha256-VkStGTQYgUctkdETzlBlOeZYccYA9ARXoWt4mvqjujI=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./fav-v0.2.11/Cargo.lock;
      outputHashes = {
        
      };
    };
  };
  firefox-utils = {
    pname = "firefox-utils";
    version = "b013243f1916576166a02d816651c2cc6416f63e";
    src = fetchurl {
      url = "https://github.com/xiaoxiaoflood/firefox-scripts/raw/b013243f1916576166a02d816651c2cc6416f63e/utils.zip";
      sha256 = "sha256-2LK3BGKSsFeMKLsXnMNz2ONJ/Wb07VTLSu4TwemYNOQ=";
    };
    date = "2023-02-24";
  };
  fx-folder = {
    pname = "fx-folder";
    version = "b013243f1916576166a02d816651c2cc6416f63e";
    src = fetchurl {
      url = "https://github.com/xiaoxiaoflood/firefox-scripts/raw/b013243f1916576166a02d816651c2cc6416f63e/fx-folder.zip";
      sha256 = "sha256-IAiHzJ/9YBuChVTePMmXFYtx69jX+crDe1GcAcfZ+OI=";
    };
    date = "2023-02-24";
  };
  go-musicfox = {
    pname = "go-musicfox";
    version = "v4.3.3";
    src = fetchFromGitHub {
      owner = "go-musicfox";
      repo = "go-musicfox";
      rev = "v4.3.3";
      fetchSubmodules = false;
      sha256 = "sha256-J6R3T92cHFUkKwc+GKm612tVjglP2Tc/kDUmzUMhvio=";
    };
  };
  httpx = {
    pname = "httpx";
    version = "0.27.0";
    src = fetchFromGitHub {
      owner = "encode";
      repo = "httpx";
      rev = "0.27.0";
      fetchSubmodules = false;
      sha256 = "sha256-13EnSzrCkseK6s6Yz9OpLzqo/2PTFiB31m5fAIJLoZg=";
    };
  };
  iina = {
    pname = "iina";
    version = "1.3.4";
    src = fetchurl {
      url = "https://github.com/iina/iina/releases/download/v1.3.4/IINA.v1.3.4.dmg";
      sha256 = "sha256-feUPWtSi/Vsnv1mjGyBgB0wFMxx6r6UzrUratlAo14w=";
    };
  };
  iinaplus = {
    pname = "iinaplus";
    version = "0.7.22";
    src = fetchurl {
      url = "https://github.com/xjbeta/iina-plus/releases/download/0.7.22/IINA+.0.7.22.dmg";
      sha256 = "sha256-s7CE9g7llVCOLwT4HiVOMdshmWc5sOpFoee6D91Gj5w=";
    };
  };
  lazyvim-star = {
    pname = "lazyvim-star";
    version = "75625b29e8891938218043a7d619d67f79666a8d";
    src = fetchFromGitHub {
      owner = "LazyVim";
      repo = "starter";
      rev = "75625b29e8891938218043a7d619d67f79666a8d";
      fetchSubmodules = false;
      sha256 = "sha256-mZbQVDh6T3GylIPvMGFV9Sp4Oc6TMiqUYW8nPATs+dE=";
    };
    date = "2024-03-29";
  };
  localsend = {
    pname = "localsend";
    version = "1.14.0";
    src = fetchurl {
      url = "https://github.com/localsend/localsend/releases/download/v1.14.0/LocalSend-1.14.0.dmg";
      sha256 = "sha256-L7V48QoOA0cjx45n+9Xav/zzCzCsZB3TBip0WGusMXg=";
    };
  };
  lporg = {
    pname = "lporg";
    version = "v20.4.31";
    src = fetchFromGitHub {
      owner = "blacktop";
      repo = "lporg";
      rev = "v20.4.31";
      fetchSubmodules = false;
      sha256 = "sha256-A/OE67qAn9RHSCveiRwG5lPYNTMdrbUWVfQOP3XjkdU=";
    };
    vendorHash = "sha256-GQaIfUtM3iDQ9jmrSMqYvcPysigdu7w10xGDIYv4OY8=";
  };
  lyricx = {
    pname = "lyricx";
    version = "1.6.4";
    src = fetchurl {
      url = "https://github.com/go-musicfox/LyricsX/releases/download/v1.6.4/LyricsX_1.6.4.zip";
      sha256 = "sha256-xEj0jin2aLQlOcPVITmL14ZVLGKAm1wZf8f4FuLmVB0=";
    };
  };
  maple-mono = {
    pname = "maple-mono";
    version = "6.4";
    src = fetchurl {
      url = "https://github.com/subframe7536/maple-font/releases/download/v6.4/MapleMono-ttf.zip";
      sha256 = "sha256-a06JLIP5aVb9SeEz6kw+LqKy0ydCgaUlPDFWA2Y0G8Q=";
    };
  };
  maple-sc-nf = {
    pname = "maple-sc-nf";
    version = "6.4";
    src = fetchurl {
      url = "https://github.com/subframe7536/Maple-font/releases/download/v6.4/MapleMono-SC-NF.zip";
      sha256 = "sha256-SbXWkrpLJUrq+Jt1h3GBP9md5TbYpPchdiR0oEDMAgY=";
    };
  };
  mihomo = {
    pname = "mihomo";
    version = "v1.18.3";
    src = fetchFromGitHub {
      owner = "MetaCubeX";
      repo = "mihomo";
      rev = "v1.18.3";
      fetchSubmodules = false;
      sha256 = "sha256-/fFVUI++OhOer5DrvcXO+R+4whtb5+3Qg3e4+ikJr1Y=";
    };
    vendorHash = "sha256-k4xB/jO78VGD+n9HtuoWXoXB+kZCEyPKJTTwj32nGIw=";
  };
  musicdl = {
    pname = "musicdl";
    version = "ae213b2e5867fa12a6fa2789e24ea792aab38540";
    src = fetchFromGitHub {
      owner = "CharlesPikachu";
      repo = "musicdl";
      rev = "ae213b2e5867fa12a6fa2789e24ea792aab38540";
      fetchSubmodules = false;
      sha256 = "sha256-AoMtlyRiceDzNXKz1K/EH5+/yU2B+UlEso5kjL5ojlI=";
    };
    date = "2023-02-22";
  };
  musicn = {
    pname = "musicn";
    version = "v1.5.0";
    src = fetchFromGitHub {
      owner = "zonemeen";
      repo = "musicn";
      rev = "v1.5.0";
      fetchSubmodules = false;
      sha256 = "sha256-jnS3NwxguAu4SJNFTvk6HgYF0eVw8/L7qC4o1K+WVwE=";
    };
    npmDepsHash = "sha256-Yr0zgQBP/ocJ/ThbFhidPnkP4C8/lWufxkd3sJnqErA=";
  };
  neovide = {
    pname = "neovide";
    version = "0.12.2";
    src = fetchurl {
      url = "https://github.com/neovide/neovide/releases/download/0.12.2/neovide.dmg.zip";
      sha256 = "sha256-cCLswmyKXMwG0RTJWMFFcgdfWyaU9saTgrsZwJuFA1A=";
    };
  };
  next-chat = {
    pname = "next-chat";
    version = "2.11.3";
    src = fetchurl {
      url = "https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/releases/download/v2.11.3/NextChat_2.11.3_universal.dmg";
      sha256 = "sha256-A8Zn2b0KatwGSIVYPP+uyxIrPPRh6gtJ97+/fOgZQ5c=";
    };
  };
  pngpaste = {
    pname = "pngpaste";
    version = "0.2.3";
    src = fetchFromGitHub {
      owner = "jcsalterego";
      repo = "pngpaste";
      rev = "0.2.3";
      fetchSubmodules = false;
      sha256 = "sha256-uvajxSelk1Wfd5is5kmT2fzDShlufBgC0PDCeabEOSE=";
    };
  };
  qbittorrent = {
    pname = "qbittorrent";
    version = "release-4.6.4.10";
    src = fetchFromGitHub {
      owner = "c0re100";
      repo = "qBittorrent-Enhanced-Edition";
      rev = "release-4.6.4.10";
      fetchSubmodules = false;
      sha256 = "sha256-wrkc11H4t96D6qr9N/2CzG93zeNv7I1g9ieXyc4x5wk=";
    };
  };
  qutebrowser = {
    pname = "qutebrowser";
    version = "3.1.0";
    src = fetchurl {
      url = "https://github.com/qutebrowser/qutebrowser/releases/download/v3.1.0/qutebrowser-3.1.0.dmg";
      sha256 = "sha256-AvuuwUnxMcr2ekZ/O1FL/4IizV1aTMhXNrbf1SwNY7U=";
    };
  };
  ryujinx = {
    pname = "ryujinx";
    version = "1.1.1262";
    src = fetchurl {
      url = "https://github.com/Ryujinx/release-channel-master/releases/download/1.1.1262/ryujinx-1.1.1262-macos_universal.app.tar.gz";
      sha256 = "sha256-YNrYsd394sGZkFnG+ZM5+5lGslLQkAOmU/zeasGxav8=";
    };
  };
  ryusak = {
    pname = "ryusak";
    version = "1.6.3";
    src = fetchurl {
      url = "https://github.com/FennyFatal/RyuSAK/releases/download/v1.6.3-experimental/RyuSAK-darwin-arm64-1.6.3.zip";
      sha256 = "sha256-iohH/P56qaFnrS/WhoNxZr66h8cdwCuFfCUDfHF1tho=";
    };
  };
  seam = {
    pname = "seam";
    version = "v_cli.0.1.39";
    src = fetchFromGitHub {
      owner = "Borber";
      repo = "seam";
      rev = "v_cli.0.1.39";
      fetchSubmodules = false;
      sha256 = "sha256-rWbswgVQNA006gi9G+Vma+y0NbMDC0/P6SqHwxxvky8=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./seam-v_cli.0.1.39/Cargo.lock;
      outputHashes = {
        
      };
    };
  };
  sidebery = {
    pname = "sidebery";
    version = "v5.2.0";
    src = fetchFromGitHub {
      owner = "mbnuqw";
      repo = "sidebery";
      rev = "v5.2.0";
      fetchSubmodules = false;
      sha256 = "sha256-83n0aX5mJYf1yYamuM+DelkpOGLRZqkXpTgQMAmMLXI=";
    };
  };
  spotube = {
    pname = "spotube";
    version = "3.5.0";
    src = fetchurl {
      url = "https://github.com/KRTirtho/spotube/releases/download/v3.5.0/Spotube-macos-universal.dmg";
      sha256 = "sha256-omXhiH/hVxFef03GqmpYf65SfdLjLyeMyuAWuvSpYiI=";
    };
  };
  switchaudio-osx = {
    pname = "switchaudio-osx";
    version = "1.2.2";
    src = fetchFromGitHub {
      owner = "deweller";
      repo = "switchaudio-osx";
      rev = "1.2.2";
      fetchSubmodules = false;
      sha256 = "sha256-AZJn5kHK/al94ONfIHcG+W0jyMfgdJkIngN+PVj+I44=";
    };
  };
  upic = {
    pname = "upic";
    version = "0.21.1";
    src = fetchurl {
      url = "https://github.com/gee1k/uPic/releases/download/v0.21.1/uPic.zip";
      sha256 = "sha256-EVLi85lcwz0W12Q0hhinCp+wZ/Kxf1SKgTZGgJqhFUw=";
    };
  };
  vivaldi = {
    pname = "vivaldi";
    version = "6.6.3271.57";
    src = fetchurl {
      url = "https://downloads.vivaldi.com/stable/Vivaldi.6.6.3271.57.universal.dmg";
      sha256 = "sha256-5pdlHD6zdqDyRZRn3JPNHNjT9CE6rCAQNG4WYLl8gbs=";
    };
  };
  websocket-bridge-python = {
    pname = "websocket-bridge-python";
    version = "0.0.2";
    src = fetchurl {
      url = "https://pypi.org/packages/source/w/websocket_bridge_python/websocket_bridge_python-0.0.2.tar.gz";
      sha256 = "sha256-J9HGD3PSavZQwh2eZPbM6isdknZ1M2nkL5WHlYjRju8=";
    };
  };
  wiliwili = {
    pname = "wiliwili";
    version = "1.3.0";
    src = fetchurl {
      url = "https://github.com/xfangfang/wiliwili/releases/download/v1.3.0/wiliwili-macOS-AppleSilicon.dmg";
      sha256 = "sha256-mo23N8UMUWXBrLFXqa0FGDqBwSPy7CMVPel1iPLF/nk=";
    };
  };
  yabai = {
    pname = "yabai";
    version = "v7.1.0";
    src = fetchFromGitHub {
      owner = "koekeishiya";
      repo = "yabai";
      rev = "v7.1.0";
      fetchSubmodules = false;
      sha256 = "sha256-5iC1U6tyUYFLjOfnIxCrjCjj2deUZ/rvsJN4jlrr2Tc=";
    };
  };
  yabai-zsh-completions = {
    pname = "yabai-zsh-completions";
    version = "6e38681a002e13bdcd43f461f73c53b7c11fd4e5";
    src = fetchFromGitHub {
      owner = "Amar1729";
      repo = "yabai-zsh-completions";
      rev = "6e38681a002e13bdcd43f461f73c53b7c11fd4e5";
      fetchSubmodules = false;
      sha256 = "sha256-II00E32Pnt7PO+PcTtWp4NzSUDhQJTgAPw9HdlItbhQ=";
    };
    date = "2023-11-13";
  };
  yutto = {
    pname = "yutto";
    version = "v2.0.0-beta.37";
    src = fetchFromGitHub {
      owner = "yutto-dev";
      repo = "yutto";
      rev = "v2.0.0-beta.37";
      fetchSubmodules = false;
      sha256 = "sha256-daRuFYfR3FjvhVsQM1FXI19iOH+bukh6WxfH5O+CFk4=";
    };
  };
  zpmod = {
    pname = "zpmod";
    version = "v1.1.0";
    src = fetchFromGitHub {
      owner = "z-shell";
      repo = "zpmod";
      rev = "v1.1.0";
      fetchSubmodules = false;
      sha256 = "sha256-vCQOn+8l9DcVJ6XbtHhr7N5IDr2Ht/JRub217ZO96Ok=";
    };
  };
  zy-player = {
    pname = "zy-player";
    version = "3.3.3";
    src = fetchurl {
      url = "https://github.com/Hiram-Wong/ZyPlayer/releases/download/v3.3.3/zyplayer-mac-3.3.3-arm64.dmg";
      sha256 = "sha256-WWooOgoPfZyZIr4YKCR4iafakZ8RqizoEopdevpBu1c=";
    };
  };
}
