#!/usr/bin/env bash
#

wm_msg=( $(bspc wm -d | jq -r '.monitors[0] | .name as $n | .rectangle | "\($n)\t\(.width)\t\(.height)"') )
wmtitle=$(xtitle $1)

_printf_int() {
    local result=$(echo "$@" | bc)
    printf "%.0f" ${result}
}

case $wmtitle in
    Escratch)
        _width=$(_printf_int "${wm_msg[1]} * 0.5")
        _height=$(_printf_int "${wm_msg[2]} * 0.5")
        _x=$((${wm_msg[1]} - ${_width}))
        _y=$((${wm_msg[2]} - ${_height}))
        echo "state=floating"
        echo "center=off"
        echo "border=off"
        echo "rectangle=${_width}x${_height}+${_x}+${_y}"
        ;;
    'File Upload')
        _width=$(_printf_int "${wm_msg[1]} * 0.618")
        _height=$(_printf_int "${wm_msg[2]} * 0.618")
        echo "state=floating"
        echo "center=on"
        echo "border=on"
        echo "rectangle=${_width}x${_height}+0+0"
        ;;
esac
