#!/usr/bin/env bash
#

wid=$1
class=$2
instance=$3
consequences=$4

wm_msg=( $(bspc wm -d | jq -r '.monitors[0] | .name as $n | .rectangle | "\($n)\t\(.width)\t\(.height)"') )
wMsg=$(xprop -id $wid)
wmTitle=$(echo -e "$wMsg" | awk -F'"' '/^WM_NAME/ {printf $2}')
wmRole=$(echo -e "$wMsg" | awk -F '"' '/^WM_WINDOW_ROLE/ {print $2}')

_multip_int() { echo "$1 $2" | awk '{printf("%.0f", $1*$2)}'; }

case "$role" in
  quake) #Tilix Quake
    echo "state=floating"
    echo "border=off"
  ;;
  pop-up|bubble|task_dialog|Preferences|dialog|menu)
    echo "state=floating"
   ;;
  About|Organizer|Buscando) #Firefox
    echo "state=floating"
  ;;
  *)
    case $wmTitle in
      Escratch)
        _width=$(_multip_int ${wm_msg[1]} 0.5)
        _height=$(_multip_int ${wm_msg[2]}  0.5)
        _x=$((${wm_msg[1]} - ${_width}))
        _y=$((${wm_msg[2]} - ${_height}))
        echo "state=floating"
        echo "center=off"
        echo "border=off"
        echo "rectangle=${_width}x${_height}+${_x}+${_y}"
      ;;
      'File Upload')
        _width=$(_multip_int  ${wm_msg[1]} 0.618)
        _height=$(_multip_int ${wm_msg[2]} 0.618)
        echo "state=floating"
        echo "center=on"
        echo "border=on"
        echo "rectangle=${_width}x${_height}+0+0"
      ;;
    esac
  ;;
esac

