#!/usr/bin/env bash

# Specifying the icon(s) in the script
# This allows us to change its appearance conditionally
pgrep redshift &> /dev/null
if [[ $? -eq 0 ]]; then
    temp=$(redshift -p 2>/dev/null | grep temp | cut -d' ' -f3)
    temp=${temp//K/}
fi
function get_colors() { xrdb -query | grep "color$1:" | cut -f2 ; }
icon=""
# OPTIONAL: Append ' ${temp}K' after $icon
if [[ -z $temp ]]; then
    echo "%{F$(get_colors 240)}$icon"       # Greyed out (not running)
elif [[ $temp -ge 5000 ]]; then
    echo "%{F$(get_colors 4)}$icon"       # Blue
elif [[ $temp -ge 4000 ]]; then
    echo "%{F$(get_colors 3)}$icon"       # Yellow
else
    echo "%{F$(get_colors 1)}$icon"       # Orange
fi
