#!/usr/bin/env sh

bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config border_width 1
bspc config window_gap 0

# Extra padding for polybar
bspc config -m primary top_padding 18
bspc config -m primary bottom_padding 0
