# declare -x -A ZINIT=(
#   [HOME_DIR]="$XDG_CACHE_HOME/zinit"
#   [BIN_DIR]="$XDG_CACHE_HOME/zinit/bin"
# )
typeset -g -A ZINIT=(
    BIN_DIR         $XDG_CACHE_HOME/zinit/bin
    HOME_DIR        $XDG_CACHE_HOME/zinit
    ZCOMPDUMP_PATH  $ZSH_CACHE
    COMPINIT_OPTS   -C
)
[[ -d "${ZINIT[BIN_DIR]}" ]] || {
  git clone --depth 1 https://github.com/zdharma/zinit "${ZINIT[BIN_DIR]}"
}
source "${ZINIT[BIN_DIR]}/zinit.zsh"
zinit ice depth"1" pick"autopair.zsh"
zinit light hlissner/zsh-autopair

zinit ice depth"1" wait"1" silent
zinit light zsh-users/zsh-history-substring-search

# zinit ice compile'(pure|async).zsh' pick'async.zsh' src'pure.zsh'
# zinit light sindresorhus/pure

zinit ice depth"1" wait"1" silent
zinit light zdharma/history-search-multi-word

zinit ice depth"1" blockf atpull'zinit creinstall -q .'
zinit light zsh-users/zsh-completions


#zinit pack for fzf
if command -v fzf >/dev/null ; then
  zinit ice lucid ver'master' wait'0b' has'fzf' pick'shell/completion.zsh' \
    src'shell/key-bindings.zsh'
  zinit light junegunn/fzf
elif command -v go >/dev/null ; then
  # see@https://zdharma.org/zinit/wiki/Zinit-Packages/#introductory_example
  zinit lucid as=program pick="$ZPFX/bin/(fzf|fzf-tmux)" \
    atclone="cp shell/completion.zsh _fzf_completion; \
      cp bin/(fzf|fzf-tmux) $ZPFX/bin"\
    make="PREFIX=$ZPFX install" for \
      junegunn/fzf
else
  # see@https://zdharma.org/zinit/wiki/GALLERY/
  zinit ice depth"1" from"gh-r" as"program"
  zinit light junegunn/fzf-bin
  zinit ice lucid ver'master' wait'0b' has'fzf' pick'shell/completion.zsh' \
    src'shell/key-bindings.zsh'
  zinit light junegunn/fzf
fi

# 快速目录跳转
zinit ice lucid wait='1' depth="1"
zinit light skywind3000/z.lua

# # fast syntax highlight
[[ -z $SSH_CONNECTION ]] && {
  # see@https://github.com/zdharma/fast-syntax-highlighting#features
  zinit ice depth"1" wait"1" lucid \
    atinit"ZINIT[COMPINIT_OPTS]=-C; zicompinit; zicdreplay"
  zinit light zdharma/fast-syntax-highlighting
}
autoload -Uz compinit && compinit -u -d $ZSH_CACHE/zcompdump
source $ZDOTDIR/config.zsh
if [[ $TERM != dumb ]]; then
  source $ZDOTDIR/keybinds.zsh
  source $ZDOTDIR/completion.zsh
  source $ZDOTDIR/aliases.zsh

#   ##
  function _cache {
    command -v "$1" >/dev/null || return 1
    local cache_dir="$XDG_CACHE_HOME/${SHELL##*/}"
    local cache="$cache_dir/$1"
    if [[ ! -f $cache || ! -s $cache ]]; then
      echo "Caching $1"
      mkdir -p $cache_dir
      "$@" >$cache
    fi
    source $cache || rm -f $cache
  }

  # fd > find
  if command -v fd >/dev/null; then
    export FZF_DEFAULT_OPTS="--reverse --ansi"
    export FZF_DEFAULT_COMMAND="fd ."
    export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
    export FZF_ALT_C_COMMAND="fd -t d . $HOME"
  fi
  ## Auto-generated by my nix config
  source $ZDOTDIR/extra.zshrc
  ##
  autopair-init

  # If you have host-local configuration, this is where you'd put it
  if [[ -f ~/.zshrc ]] ; then
    source ~/.zshrc
  fi
fi
