#!/usr/bin/env bash

[[ -f $HOME/.profile ]] && source $HOME/.profile

X11_HOME=${XDG_CONFIG_HOME:-$HOME/.config}/X11

_get_user_files() {
    if [[ -f $X11_HOME/$1 ]]; then
        echo $X11_HOME/$1
    elif [[ -f $HOME/.$1 ]]; then
        echo $HOME/.$1
    fi
}

user_resource=$(_get_user_files "Xresources")
user_xmodmap=$(_get_user_files "Xmodmap")
sysresource=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap


[[ -f $sysresource ]] && xrdb -merge $sysresource
[[ -f $sysmodmap ]]   && xmodmap $sysmodmap
[[ -n $user_resource ]] && xrdb -merge $user_resource
[[ -n $user_xmodmap ]] && xmodmap $user_xmodmap

unset user_resource user_resource sysmodmap sysresource
# Start some nice programs
if [[ -d /etc/X11/xinit/xinitrc.d ]]; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
        [[ -x "$f" ]] && . "$f"
    done
    unset f
fi

export __INIT_X11=1

session=${1:-awesome}
cmd="dbus-launch --sh-syntax --exit-with-session"
case $session in
	awesome         ) exec $cmd awesome;;
	jwm             ) exec $cmd jwm;;
	deepin          ) exec $cmd startdde;;
	enlightenment   ) exec $cmd enlightenment_start;;
	gnome           ) exec $cmd gnome-session;;
	bspwm           ) exec $cmd bspwm-session;;
    lxde            ) exec $cmd startlxde;;
    lxqt            ) exec $cmd lxqt-session;;
    i3|i3wm         ) exec $cmd i3;;
    kde             ) exec $cmd startkde;;
    cinnamon        ) exec $cmd cinnamon-session;;
    budgie          ) exec $cmd budgie-desktop;;
    mate            ) exec $cmd mate-session;;
    openbox         ) exec $cmd openbox-session;;
    xfce|xfce4      ) exec $cmd startxfce4;;
    # No known session, try to run it as command
    *               ) exec $cmd "$1";;
esac
