#!/usr/bin/env bash

[[ -f $HOME/.profile ]] && source $HOME/.profile

X11_HOME=${XDG_CONFIG_HOME:-$HOME/.config}/X11

_get_user_files() {
    if [[ -f $X11_HOME/$1 ]]; then
        echo $X11_HOME/$1
    elif [[ -f $HOME/.$1 ]]; then
        echo $HOME/.$1
    fi
}

user_resource=$(_get_user_files "Xresources")
user_xmodmap=$(_get_user_files "Xmodmap")
sysresource=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap


[[ -f $sysresource ]] && xrdb -merge $sysresource
[[ -f $sysmodmap ]]   && xmodmap $sysmodmap
[[ -n $user_resource ]] && xrdb -merge $user_resource
[[ -n $user_xmodmap ]] && xmodmap $user_xmodmap

unset user_resource user_resource sysmodmap sysresource
# Start some nice programs
if [[ -d /etc/X11/xinit/xinitrc.d ]]; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
        [[ -x "$f" ]] && . "$f"
    done
    unset f
fi

export __INIT_X11=1

session=${1:-awesome}

case $session in
	awesome 		  ) exec dbus-launch --sh-syntax --exit-with-session awesome;;
	jwm 			  ) exec dbus-launch --sh-syntax --exit-with-session jwm;;
	deepin 			  ) exec dbus-launch --sh-syntax --exit-with-session startdde;;
	enlightenment 	  ) exec dbus-launch --sh-syntax --exit-with-session enlightenment_start;;
	gnome 			  ) exec dbus-launch --sh-syntax --exit-with-session gnome-session;;
	bspwm 			  ) exec dbus-launch --sh-syntax --exit-with-session bspwm-session;;
    lxde 	          ) exec dbus-launch --sh-syntax --exit-with-session startlxde;;
    lxqt         	  ) exec dbus-launch --sh-syntax --exit-with-session lxqt-session;;
    i3|i3wm           ) exec dbus-launch --sh-syntax --exit-with-session i3;;
    kde               ) exec dbus-launch --sh-syntax --exit-with-session startkde;;
    cinnamon          ) exec dbus-launch --sh-syntax --exit-with-session cinnamon-session;;
    budgie            ) exec dbus-launch --sh-syntax --exit-with-session budgie-desktop;;
    mate              ) exec dbus-launch --sh-syntax --exit-with-session mate-session;;
    openbox           ) exec dbus-launch --sh-syntax --exit-with-session openbox-session;;
    xfce|xfce4        ) exec dbus-launch --sh-syntax --exit-with-session startxfce4;;
    # No known session, try to run it as command
    *                 ) exec dbus-launch --sh-syntax --exit-with-session "$1";;
esac
