name: Auto Update Flake Inputs

on:
  schedule:
    # run this daily at 8am UTC, or roughly 4am eastern
    - cron: '30 2 * * 6'
  # Allows you to run this workflow manually from the Actions tab
  # push:
  #   branches:
  #     - master
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      # - uses: styfle/cancel-workflow-action@0.7.0
      #   with:
      #     access_token: ${{ github.token }}
      - uses: actions/checkout@v4
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - uses: cachix/install-nix-action@v25
        with:
          # FIXME: https://github.com/NixOS/nix/issues/9889
          extra_nix_config: |
            experimental-features = nix-command flakes configurable-impure-env auto-allocate-uids
      - name: Prepare flakebot branch
        run: |
          git config --local user.email "flakebot@users.noreply.github.com"
          git config --local user.name "flakebot"
          git checkout -B flakebot
      - name: Update and commit lockfile
        # run: nix flake update --commit-lock-file
        run: nix run -v --impure .#update
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: flakebot
          force: true
      - name: pull-request-action
        uses: vsoch/pull-request-action@1.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_REQUEST_FROM_BRANCH: 'flakebot'
          PULL_REQUEST_BRANCH: 'master'
          MAINTAINER_CANT_MODIFY: true
          PASS_IF_EXISTS: true
          PASS_ON_ERROR: true
          PULL_REQUEST_UPDATE: true
          PULL_REQUEST_TITLE: 'Update Flake Inputs'

  test_update_ci:
    needs:
      - update
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          # Shallow clones won't work
          fetch-depth: 0
      - uses: cachix/install-nix-action@v25
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
            # access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Prepare flakebot branch
        run: |
          git config --local user.email "flakebot@users.noreply.github.com"
          git config --local user.name "flakebot"
          git checkout -b flakebot
          git branch --set-upstream-to=origin/flakebot
          git pull
      - uses: cachix/cachix-action@v14
        with:
          name: shanyouli
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      # - name: Print CPU info
      #   run: |
      #     echo "Cores: $(nproc), Arch: $(uname -p)"
      - name: Run Flake Checks
        run: |
          nix flake check --show-trace --impure
          # nix run --impure .#checks
          # if [[ $(uname) == "Darwin" ]]; then
          #   nix run -v --experimental-features "nix-command flakes" --extra-substituters https://shanyouli.cachix.org --impure github:nix-community/home-manager --no-write-lock-file -- build --flake .#test@aarch64-darwin -b backup --show-trace
          # else
          #   nix run -v --experimental-features "nix-command flakes" --extra-substituters https://shanyouli.cachix.org --impure github:nix-community/home-manager --no-write-lock-file -- build --flake .#test@x86_64-linux -b backup --show-trace
          # fi
        timeout-minutes: 240

  merge-to-master:
    needs:
      - test_update_ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - name: Prepare flakebot branch
        run: |
          git config --local user.email "flakebot@users.noreply.github.com"
          git config --local user.name "flakebot"
          git checkout -b flakebot
          git branch --set-upstream-to=origin/flakebot
          git pull
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true
