name: Auto Update Flake Inputs

on:
  schedule:
    # run this daily at 8am UTC, or roughly 4am eastern
    - cron: "30 2 * * 6"
  # Allows you to run this workflow manually from the Actions tab
  # push:
  #   branches:
  #     - master
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      # - uses: styfle/cancel-workflow-action@0.7.0
      #   with:
      #     access_token: ${{ github.token }}
      - uses: actions/checkout@v6
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - uses: cachix/install-nix-action@v31
        with:
          # FIXME: https://github.com/NixOS/nix/issues/9889
          extra_nix_config: |
            experimental-features = nix-command flakes configurable-impure-env auto-allocate-uids
      - name: Setup Nushell
        uses: hustcer/setup-nu@v3
      - name: Setup just
        uses: extractions/setup-just@v4
      - name: Prepare flakebot branch
        run: |
          git config --local user.email "flakebot@users.noreply.github.com"
          git config --local user.name "flakebot"
          git checkout -B flakebot
      - name: Update flake inputs
        id: update
        run: |
          set -euo pipefail
          before_commit="$(git rev-parse HEAD)"
          just ci update
          after_commit="$(git rev-parse HEAD)"
          if [[ "$before_commit" == "$after_commit" ]]; then
            echo "changed=false" >> "$GITHUB_OUTPUT"
            echo "No flake input changes."
          else
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi
      - name: Push changes
        if: steps.update.outputs.changed == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: flakebot
          force: true
      - name: pull-request-action
        if: steps.update.outputs.changed == 'true'
        uses: vsoch/pull-request-action@1.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_REQUEST_FROM_BRANCH: "flakebot"
          PULL_REQUEST_BRANCH: "master"
          MAINTAINER_CANT_MODIFY: true
          PASS_IF_EXISTS: true
          PASS_ON_ERROR: true
          PULL_REQUEST_UPDATE: true
          PULL_REQUEST_TITLE: "Update Flake Inputs"
      - name: Trigger second workflow
        if: steps.update.outputs.changed == 'true'
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.everest-preview+json" \
          https://api.github.com/repos/${{ github.repository }}/dispatches \
          -d '{"event_type": "Build-check"}'
